# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.api_key_user_details import ApiKeyUserDetails
from ..types.paginated_api_api_user import PaginatedApiApiUser
from ..types.paginated_api_user_access_list_response import PaginatedApiUserAccessListResponse
from ..types.user_access_list_request import UserAccessListRequest
from ..types.user_access_list_response import UserAccessListResponse
from ..types.user_access_role_assignment import UserAccessRoleAssignment
from .raw_client import AsyncRawProgrammaticApiKeysClient, RawProgrammaticApiKeysClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class ProgrammaticApiKeysClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawProgrammaticApiKeysClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawProgrammaticApiKeysClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawProgrammaticApiKeysClient
        """
        return self._raw_client

    def list_group_api_keys(
        self,
        group_id: str,
        *,
        include_count: typing.Optional[bool] = None,
        items_per_page: typing.Optional[int] = None,
        page_num: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PaginatedApiApiUser:
        """
        Returns all organization API keys that you assigned to the specified project. Users with the Project Owner role in the project associated with the API key can use the organization API key to access the resources. To use this resource, the requesting Service Account or API Key must have the Project Owner role.

        Parameters
        ----------
        group_id : str
            Unique 24-hexadecimal digit string that identifies your project. Use the [/groups](#tag/Projects/operation/listProjects) endpoint to retrieve all projects to which the authenticated user has access.

            **NOTE**: Groups and projects are synonymous terms. Your group id is the same as your project id. For existing groups, your group/project id remains the same. The resource and corresponding endpoints use the term groups.

        include_count : typing.Optional[bool]
            Flag that indicates whether the response returns the total number of items (`totalCount`) in the response.

        items_per_page : typing.Optional[int]
            Number of items that the response returns per page.

        page_num : typing.Optional[int]
            Number of the page that displays the current set of the total objects that the response returns.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PaginatedApiApiUser
            OK

        Examples
        --------
        from atlas_sdk import AtlasClient

        client = AtlasClient(
            token="YOUR_TOKEN",
        )
        client.programmatic_api_keys.list_group_api_keys(
            group_id="32b6e34b3d91647abb20e7b8",
        )
        """
        _response = self._raw_client.list_group_api_keys(
            group_id,
            include_count=include_count,
            items_per_page=items_per_page,
            page_num=page_num,
            request_options=request_options,
        )
        return _response.data

    def create_group_api_key(
        self,
        group_id: str,
        *,
        desc: str,
        roles: typing.Sequence[str],
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ApiKeyUserDetails:
        """
        Creates and assigns the specified organization API key to the specified project. Users with the Project Owner role in the project associated with the API key can use the organization API key to access the resources. To use this resource, the requesting Service Account or API Key must have the Project Owner role or Project Access Manager role.

        Parameters
        ----------
        group_id : str
            Unique 24-hexadecimal digit string that identifies your project. Use the [/groups](#tag/Projects/operation/listProjects) endpoint to retrieve all projects to which the authenticated user has access.

            **NOTE**: Groups and projects are synonymous terms. Your group id is the same as your project id. For existing groups, your group/project id remains the same. The resource and corresponding endpoints use the term groups.

        desc : str
            Purpose or explanation provided when someone created this project API key.

        roles : typing.Sequence[str]
            List of roles to grant this API key. If you provide this list, provide a minimum of one role and ensure each role applies to this project.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ApiKeyUserDetails
            OK

        Examples
        --------
        from atlas_sdk import AtlasClient

        client = AtlasClient(
            token="YOUR_TOKEN",
        )
        client.programmatic_api_keys.create_group_api_key(
            group_id="32b6e34b3d91647abb20e7b8",
            desc="desc",
            roles=["roles"],
        )
        """
        _response = self._raw_client.create_group_api_key(
            group_id, desc=desc, roles=roles, request_options=request_options
        )
        return _response.data

    def add_group_api_key(
        self,
        group_id: str,
        api_user_id: str,
        *,
        request: typing.Sequence[UserAccessRoleAssignment],
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.Any:
        """
        Assigns the specified organization API key to the specified project. Users with the Project Owner role in the project associated with the API key can then use the organization API key to access the resources. To use this resource, the requesting Service Account or API Key must have the Project Owner role.

        Parameters
        ----------
        group_id : str
            Unique 24-hexadecimal digit string that identifies your project. Use the [/groups](#tag/Projects/operation/listProjects) endpoint to retrieve all projects to which the authenticated user has access.

            **NOTE**: Groups and projects are synonymous terms. Your group id is the same as your project id. For existing groups, your group/project id remains the same. The resource and corresponding endpoints use the term groups.

        api_user_id : str
            Unique 24-hexadecimal digit string that identifies this organization API key that you want to assign to one project.

        request : typing.Sequence[UserAccessRoleAssignment]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Any
            This endpoint does not return a response body.

        Examples
        --------
        from atlas_sdk import AtlasClient, UserAccessRoleAssignment

        client = AtlasClient(
            token="YOUR_TOKEN",
        )
        client.programmatic_api_keys.add_group_api_key(
            group_id="32b6e34b3d91647abb20e7b8",
            api_user_id="apiUserId",
            request=[UserAccessRoleAssignment()],
        )
        """
        _response = self._raw_client.add_group_api_key(
            group_id, api_user_id, request=request, request_options=request_options
        )
        return _response.data

    def remove_group_api_key(
        self, group_id: str, api_user_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Any:
        """
        Removes one organization API key from the specified project. To use this resource, the requesting Service Account or API Key must have the Project Owner role or Project Access Manager role.

        Parameters
        ----------
        group_id : str
            Unique 24-hexadecimal digit string that identifies your project. Use the [/groups](#tag/Projects/operation/listProjects) endpoint to retrieve all projects to which the authenticated user has access.

            **NOTE**: Groups and projects are synonymous terms. Your group id is the same as your project id. For existing groups, your group/project id remains the same. The resource and corresponding endpoints use the term groups.

        api_user_id : str
            Unique 24-hexadecimal digit string that identifies this organization API key that you want to unassign from one project.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Any
            This endpoint does not return a response body.

        Examples
        --------
        from atlas_sdk import AtlasClient

        client = AtlasClient(
            token="YOUR_TOKEN",
        )
        client.programmatic_api_keys.remove_group_api_key(
            group_id="32b6e34b3d91647abb20e7b8",
            api_user_id="apiUserId",
        )
        """
        _response = self._raw_client.remove_group_api_key(group_id, api_user_id, request_options=request_options)
        return _response.data

    def update_api_key_roles(
        self,
        group_id: str,
        api_user_id: str,
        *,
        page_num: typing.Optional[int] = None,
        items_per_page: typing.Optional[int] = None,
        include_count: typing.Optional[bool] = None,
        desc: typing.Optional[str] = OMIT,
        roles: typing.Optional[typing.Sequence[str]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ApiKeyUserDetails:
        """
        Updates the roles of the organization API key that you specify for the project that you specify. You must specify at least one valid role for the project. The application removes any roles that you do not include in this request if they were previously set in the organization API key that you specify for the project. To use this resource, the requesting Service Account or API Key must have the Project Owner role or Project Access Manager role.

        Parameters
        ----------
        group_id : str
            Unique 24-hexadecimal digit string that identifies your project. Use the [/groups](#tag/Projects/operation/listProjects) endpoint to retrieve all projects to which the authenticated user has access.

            **NOTE**: Groups and projects are synonymous terms. Your group id is the same as your project id. For existing groups, your group/project id remains the same. The resource and corresponding endpoints use the term groups.

        api_user_id : str
            Unique 24-hexadecimal digit string that identifies this organization API key that you want to unassign from one project.

        page_num : typing.Optional[int]
            Number of the page that displays the current set of the total objects that the response returns.

        items_per_page : typing.Optional[int]
            Number of items that the response returns per page.

        include_count : typing.Optional[bool]
            Flag that indicates whether the response returns the total number of items (`totalCount`) in the response.

        desc : typing.Optional[str]
            Purpose or explanation provided when someone creates this project API key.

        roles : typing.Optional[typing.Sequence[str]]
            List of roles to grant this API key. If you provide this list, provide a minimum of one role and ensure each role applies to this project.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ApiKeyUserDetails
            OK

        Examples
        --------
        from atlas_sdk import AtlasClient

        client = AtlasClient(
            token="YOUR_TOKEN",
        )
        client.programmatic_api_keys.update_api_key_roles(
            group_id="32b6e34b3d91647abb20e7b8",
            api_user_id="apiUserId",
        )
        """
        _response = self._raw_client.update_api_key_roles(
            group_id,
            api_user_id,
            page_num=page_num,
            items_per_page=items_per_page,
            include_count=include_count,
            desc=desc,
            roles=roles,
            request_options=request_options,
        )
        return _response.data

    def list_org_api_keys(
        self,
        org_id: str,
        *,
        include_count: typing.Optional[bool] = None,
        items_per_page: typing.Optional[int] = None,
        page_num: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PaginatedApiApiUser:
        """
        Returns all organization API keys for the specified organization. The organization API keys grant programmatic access to an organization. You can't use the API key to log into MongoDB Cloud through the console. To use this resource, the requesting Service Account or API Key must have the Organization Member role.

        Parameters
        ----------
        org_id : str
            Unique 24-hexadecimal digit string that identifies the organization that contains your projects. Use the [`/orgs`](#tag/Organizations/operation/listOrganizations) endpoint to retrieve all organizations to which the authenticated user has access.

        include_count : typing.Optional[bool]
            Flag that indicates whether the response returns the total number of items (`totalCount`) in the response.

        items_per_page : typing.Optional[int]
            Number of items that the response returns per page.

        page_num : typing.Optional[int]
            Number of the page that displays the current set of the total objects that the response returns.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PaginatedApiApiUser
            OK

        Examples
        --------
        from atlas_sdk import AtlasClient

        client = AtlasClient(
            token="YOUR_TOKEN",
        )
        client.programmatic_api_keys.list_org_api_keys(
            org_id="4888442a3354817a7320eb61",
        )
        """
        _response = self._raw_client.list_org_api_keys(
            org_id,
            include_count=include_count,
            items_per_page=items_per_page,
            page_num=page_num,
            request_options=request_options,
        )
        return _response.data

    def create_org_api_key(
        self,
        org_id: str,
        *,
        desc: str,
        roles: typing.Sequence[str],
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ApiKeyUserDetails:
        """
        Creates one API key for the specified organization. An organization API key grants programmatic access to an organization. You can't use the API key to log into the console. To use this resource, the requesting Service Account or API Key must have the Organization Owner role.

        Parameters
        ----------
        org_id : str
            Unique 24-hexadecimal digit string that identifies the organization that contains your projects. Use the [`/orgs`](#tag/Organizations/operation/listOrganizations) endpoint to retrieve all organizations to which the authenticated user has access.

        desc : str
            Purpose or explanation provided when someone created this organization API key.

        roles : typing.Sequence[str]
            List of roles to grant this API key. If you provide this list, provide a minimum of one role and ensure each role applies to this organization.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ApiKeyUserDetails
            OK

        Examples
        --------
        from atlas_sdk import AtlasClient

        client = AtlasClient(
            token="YOUR_TOKEN",
        )
        client.programmatic_api_keys.create_org_api_key(
            org_id="4888442a3354817a7320eb61",
            desc="desc",
            roles=["roles"],
        )
        """
        _response = self._raw_client.create_org_api_key(org_id, desc=desc, roles=roles, request_options=request_options)
        return _response.data

    def get_org_api_key(
        self, org_id: str, api_user_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> ApiKeyUserDetails:
        """
        Returns one organization API key. The organization API keys grant programmatic access to an organization. You can't use the API key to log into MongoDB Cloud through the user interface. To use this resource, the requesting Service Account or API Key must have the  Organization Member role.

        Parameters
        ----------
        org_id : str
            Unique 24-hexadecimal digit string that identifies the organization that contains your projects. Use the [`/orgs`](#tag/Organizations/operation/listOrganizations) endpoint to retrieve all organizations to which the authenticated user has access.

        api_user_id : str
            Unique 24-hexadecimal digit string that identifies this organization API key that  you want to update.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ApiKeyUserDetails
            OK

        Examples
        --------
        from atlas_sdk import AtlasClient

        client = AtlasClient(
            token="YOUR_TOKEN",
        )
        client.programmatic_api_keys.get_org_api_key(
            org_id="4888442a3354817a7320eb61",
            api_user_id="apiUserId",
        )
        """
        _response = self._raw_client.get_org_api_key(org_id, api_user_id, request_options=request_options)
        return _response.data

    def delete_org_api_key(
        self, org_id: str, api_user_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Any:
        """
        Removes one organization API key from the specified organization. When you remove an API key from an organization, MongoDB Cloud also removes that key from any projects that use that key. To use this resource, the requesting Service Account or API Key must have the Organization Owner role.

        Parameters
        ----------
        org_id : str
            Unique 24-hexadecimal digit string that identifies the organization that contains your projects. Use the [`/orgs`](#tag/Organizations/operation/listOrganizations) endpoint to retrieve all organizations to which the authenticated user has access.

        api_user_id : str
            Unique 24-hexadecimal digit string that identifies this organization API key.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Any
            This endpoint does not return a response body.

        Examples
        --------
        from atlas_sdk import AtlasClient

        client = AtlasClient(
            token="YOUR_TOKEN",
        )
        client.programmatic_api_keys.delete_org_api_key(
            org_id="4888442a3354817a7320eb61",
            api_user_id="apiUserId",
        )
        """
        _response = self._raw_client.delete_org_api_key(org_id, api_user_id, request_options=request_options)
        return _response.data

    def update_org_api_key(
        self,
        org_id: str,
        api_user_id: str,
        *,
        desc: typing.Optional[str] = OMIT,
        roles: typing.Optional[typing.Sequence[str]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ApiKeyUserDetails:
        """
        Updates one organization API key in the specified organization. The organization API keys  grant programmatic access to an organization. To use this resource, the requesting  API Key must have the Organization Owner role.

        Parameters
        ----------
        org_id : str
            Unique 24-hexadecimal digit string that identifies the organization that contains your projects. Use the [`/orgs`](#tag/Organizations/operation/listOrganizations) endpoint to retrieve all organizations to which the authenticated user has access.

        api_user_id : str
            Unique 24-hexadecimal digit string that identifies this organization API key you  want to update.

        desc : typing.Optional[str]
            Purpose or explanation provided when someone creates this organization API key.

        roles : typing.Optional[typing.Sequence[str]]
            List of roles to grant this API key. If you provide this list, provide a minimum of one role and ensure each role applies to this organization.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ApiKeyUserDetails
            OK

        Examples
        --------
        from atlas_sdk import AtlasClient

        client = AtlasClient(
            token="YOUR_TOKEN",
        )
        client.programmatic_api_keys.update_org_api_key(
            org_id="4888442a3354817a7320eb61",
            api_user_id="apiUserId",
        )
        """
        _response = self._raw_client.update_org_api_key(
            org_id, api_user_id, desc=desc, roles=roles, request_options=request_options
        )
        return _response.data

    def list_org_access_entries(
        self,
        org_id: str,
        api_user_id: str,
        *,
        include_count: typing.Optional[bool] = None,
        items_per_page: typing.Optional[int] = None,
        page_num: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PaginatedApiUserAccessListResponse:
        """
        Returns all access list entries that you configured for the specified organization API key. To use this resource, the requesting Service Account or API Key must have the Organization Member role.

        Parameters
        ----------
        org_id : str
            Unique 24-hexadecimal digit string that identifies the organization that contains your projects. Use the [`/orgs`](#tag/Organizations/operation/listOrganizations) endpoint to retrieve all organizations to which the authenticated user has access.

        api_user_id : str
            Unique 24-hexadecimal digit string that identifies this organization API key for which you want to return access list entries.

        include_count : typing.Optional[bool]
            Flag that indicates whether the response returns the total number of items (`totalCount`) in the response.

        items_per_page : typing.Optional[int]
            Number of items that the response returns per page.

        page_num : typing.Optional[int]
            Number of the page that displays the current set of the total objects that the response returns.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PaginatedApiUserAccessListResponse
            OK

        Examples
        --------
        from atlas_sdk import AtlasClient

        client = AtlasClient(
            token="YOUR_TOKEN",
        )
        client.programmatic_api_keys.list_org_access_entries(
            org_id="4888442a3354817a7320eb61",
            api_user_id="apiUserId",
        )
        """
        _response = self._raw_client.list_org_access_entries(
            org_id,
            api_user_id,
            include_count=include_count,
            items_per_page=items_per_page,
            page_num=page_num,
            request_options=request_options,
        )
        return _response.data

    def create_org_access_entry(
        self,
        org_id: str,
        api_user_id: str,
        *,
        request: typing.Sequence[UserAccessListRequest],
        include_count: typing.Optional[bool] = None,
        items_per_page: typing.Optional[int] = None,
        page_num: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PaginatedApiUserAccessListResponse:
        """
        Creates the access list entries for the specified organization API key. Resources require all API requests originate from IP addresses on the API access list. To use this resource, the requesting Service Account or API Key must have the Read Write role.

        Parameters
        ----------
        org_id : str
            Unique 24-hexadecimal digit string that identifies the organization that contains your projects. Use the [`/orgs`](#tag/Organizations/operation/listOrganizations) endpoint to retrieve all organizations to which the authenticated user has access.

        api_user_id : str
            Unique 24-hexadecimal digit string that identifies this organization API key for which you want to create a new access list entry.

        request : typing.Sequence[UserAccessListRequest]

        include_count : typing.Optional[bool]
            Flag that indicates whether the response returns the total number of items (`totalCount`) in the response.

        items_per_page : typing.Optional[int]
            Number of items that the response returns per page.

        page_num : typing.Optional[int]
            Number of the page that displays the current set of the total objects that the response returns.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PaginatedApiUserAccessListResponse
            OK

        Examples
        --------
        from atlas_sdk import AtlasClient, UserAccessListRequest

        client = AtlasClient(
            token="YOUR_TOKEN",
        )
        client.programmatic_api_keys.create_org_access_entry(
            org_id="4888442a3354817a7320eb61",
            api_user_id="apiUserId",
            request=[UserAccessListRequest()],
        )
        """
        _response = self._raw_client.create_org_access_entry(
            org_id,
            api_user_id,
            request=request,
            include_count=include_count,
            items_per_page=items_per_page,
            page_num=page_num,
            request_options=request_options,
        )
        return _response.data

    def get_org_access_entry(
        self, org_id: str, api_user_id: str, ip_address: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> UserAccessListResponse:
        """
        Returns one access list entry for the specified organization API key. Resources require  all API requests originate from IP addresses on the API access list. To use this resource, the requesting Service Account or API Key must have the Organization Member role.

        Parameters
        ----------
        org_id : str
            Unique 24-hexadecimal digit string that identifies the organization that contains your projects. Use the [`/orgs`](#tag/Organizations/operation/listOrganizations) endpoint to retrieve all organizations to which the authenticated user has access.

        api_user_id : str
            Unique 24-hexadecimal digit string that identifies this organization API key for  which you want to return access list entries.

        ip_address : str
            One IP address or multiple IP addresses represented as one CIDR block to limit  requests to API resources in the specified organization. When adding a CIDR block with a subnet mask, such as  192.0.2.0/24, use the URL-encoded value %2F for the forward slash /.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        UserAccessListResponse
            OK

        Examples
        --------
        from atlas_sdk import AtlasClient

        client = AtlasClient(
            token="YOUR_TOKEN",
        )
        client.programmatic_api_keys.get_org_access_entry(
            org_id="4888442a3354817a7320eb61",
            api_user_id="apiUserId",
            ip_address="192.0.2.0%2F24",
        )
        """
        _response = self._raw_client.get_org_access_entry(
            org_id, api_user_id, ip_address, request_options=request_options
        )
        return _response.data

    def delete_access_entry(
        self, org_id: str, api_user_id: str, ip_address: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Any:
        """
        Removes the specified access list entry from the specified organization API key. Resources require all API requests originate from the IP addresses on the API access list. To use this resource, the requesting Service Account or API Key must have the Read Write role. In addition, you cannot remove the requesting IP address from the requesting organization API key.

        Parameters
        ----------
        org_id : str
            Unique 24-hexadecimal digit string that identifies the organization that contains your projects. Use the [`/orgs`](#tag/Organizations/operation/listOrganizations) endpoint to retrieve all organizations to which the authenticated user has access.

        api_user_id : str
            Unique 24-hexadecimal digit string that identifies this organization API key for which you want to remove access list entries.

        ip_address : str
            One IP address or multiple IP addresses represented as one CIDR block to limit requests to API resources in the specified organization. When adding a CIDR block with a subnet mask, such as 192.0.2.0/24, use the URL-encoded value %2F for the forward slash /.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Any
            This endpoint does not return a response body.

        Examples
        --------
        from atlas_sdk import AtlasClient

        client = AtlasClient(
            token="YOUR_TOKEN",
        )
        client.programmatic_api_keys.delete_access_entry(
            org_id="4888442a3354817a7320eb61",
            api_user_id="apiUserId",
            ip_address="192.0.2.0%2F24",
        )
        """
        _response = self._raw_client.delete_access_entry(
            org_id, api_user_id, ip_address, request_options=request_options
        )
        return _response.data


class AsyncProgrammaticApiKeysClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawProgrammaticApiKeysClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawProgrammaticApiKeysClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawProgrammaticApiKeysClient
        """
        return self._raw_client

    async def list_group_api_keys(
        self,
        group_id: str,
        *,
        include_count: typing.Optional[bool] = None,
        items_per_page: typing.Optional[int] = None,
        page_num: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PaginatedApiApiUser:
        """
        Returns all organization API keys that you assigned to the specified project. Users with the Project Owner role in the project associated with the API key can use the organization API key to access the resources. To use this resource, the requesting Service Account or API Key must have the Project Owner role.

        Parameters
        ----------
        group_id : str
            Unique 24-hexadecimal digit string that identifies your project. Use the [/groups](#tag/Projects/operation/listProjects) endpoint to retrieve all projects to which the authenticated user has access.

            **NOTE**: Groups and projects are synonymous terms. Your group id is the same as your project id. For existing groups, your group/project id remains the same. The resource and corresponding endpoints use the term groups.

        include_count : typing.Optional[bool]
            Flag that indicates whether the response returns the total number of items (`totalCount`) in the response.

        items_per_page : typing.Optional[int]
            Number of items that the response returns per page.

        page_num : typing.Optional[int]
            Number of the page that displays the current set of the total objects that the response returns.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PaginatedApiApiUser
            OK

        Examples
        --------
        import asyncio

        from atlas_sdk import AsyncAtlasClient

        client = AsyncAtlasClient(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.programmatic_api_keys.list_group_api_keys(
                group_id="32b6e34b3d91647abb20e7b8",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list_group_api_keys(
            group_id,
            include_count=include_count,
            items_per_page=items_per_page,
            page_num=page_num,
            request_options=request_options,
        )
        return _response.data

    async def create_group_api_key(
        self,
        group_id: str,
        *,
        desc: str,
        roles: typing.Sequence[str],
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ApiKeyUserDetails:
        """
        Creates and assigns the specified organization API key to the specified project. Users with the Project Owner role in the project associated with the API key can use the organization API key to access the resources. To use this resource, the requesting Service Account or API Key must have the Project Owner role or Project Access Manager role.

        Parameters
        ----------
        group_id : str
            Unique 24-hexadecimal digit string that identifies your project. Use the [/groups](#tag/Projects/operation/listProjects) endpoint to retrieve all projects to which the authenticated user has access.

            **NOTE**: Groups and projects are synonymous terms. Your group id is the same as your project id. For existing groups, your group/project id remains the same. The resource and corresponding endpoints use the term groups.

        desc : str
            Purpose or explanation provided when someone created this project API key.

        roles : typing.Sequence[str]
            List of roles to grant this API key. If you provide this list, provide a minimum of one role and ensure each role applies to this project.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ApiKeyUserDetails
            OK

        Examples
        --------
        import asyncio

        from atlas_sdk import AsyncAtlasClient

        client = AsyncAtlasClient(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.programmatic_api_keys.create_group_api_key(
                group_id="32b6e34b3d91647abb20e7b8",
                desc="desc",
                roles=["roles"],
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_group_api_key(
            group_id, desc=desc, roles=roles, request_options=request_options
        )
        return _response.data

    async def add_group_api_key(
        self,
        group_id: str,
        api_user_id: str,
        *,
        request: typing.Sequence[UserAccessRoleAssignment],
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.Any:
        """
        Assigns the specified organization API key to the specified project. Users with the Project Owner role in the project associated with the API key can then use the organization API key to access the resources. To use this resource, the requesting Service Account or API Key must have the Project Owner role.

        Parameters
        ----------
        group_id : str
            Unique 24-hexadecimal digit string that identifies your project. Use the [/groups](#tag/Projects/operation/listProjects) endpoint to retrieve all projects to which the authenticated user has access.

            **NOTE**: Groups and projects are synonymous terms. Your group id is the same as your project id. For existing groups, your group/project id remains the same. The resource and corresponding endpoints use the term groups.

        api_user_id : str
            Unique 24-hexadecimal digit string that identifies this organization API key that you want to assign to one project.

        request : typing.Sequence[UserAccessRoleAssignment]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Any
            This endpoint does not return a response body.

        Examples
        --------
        import asyncio

        from atlas_sdk import AsyncAtlasClient, UserAccessRoleAssignment

        client = AsyncAtlasClient(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.programmatic_api_keys.add_group_api_key(
                group_id="32b6e34b3d91647abb20e7b8",
                api_user_id="apiUserId",
                request=[UserAccessRoleAssignment()],
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.add_group_api_key(
            group_id, api_user_id, request=request, request_options=request_options
        )
        return _response.data

    async def remove_group_api_key(
        self, group_id: str, api_user_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Any:
        """
        Removes one organization API key from the specified project. To use this resource, the requesting Service Account or API Key must have the Project Owner role or Project Access Manager role.

        Parameters
        ----------
        group_id : str
            Unique 24-hexadecimal digit string that identifies your project. Use the [/groups](#tag/Projects/operation/listProjects) endpoint to retrieve all projects to which the authenticated user has access.

            **NOTE**: Groups and projects are synonymous terms. Your group id is the same as your project id. For existing groups, your group/project id remains the same. The resource and corresponding endpoints use the term groups.

        api_user_id : str
            Unique 24-hexadecimal digit string that identifies this organization API key that you want to unassign from one project.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Any
            This endpoint does not return a response body.

        Examples
        --------
        import asyncio

        from atlas_sdk import AsyncAtlasClient

        client = AsyncAtlasClient(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.programmatic_api_keys.remove_group_api_key(
                group_id="32b6e34b3d91647abb20e7b8",
                api_user_id="apiUserId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.remove_group_api_key(group_id, api_user_id, request_options=request_options)
        return _response.data

    async def update_api_key_roles(
        self,
        group_id: str,
        api_user_id: str,
        *,
        page_num: typing.Optional[int] = None,
        items_per_page: typing.Optional[int] = None,
        include_count: typing.Optional[bool] = None,
        desc: typing.Optional[str] = OMIT,
        roles: typing.Optional[typing.Sequence[str]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ApiKeyUserDetails:
        """
        Updates the roles of the organization API key that you specify for the project that you specify. You must specify at least one valid role for the project. The application removes any roles that you do not include in this request if they were previously set in the organization API key that you specify for the project. To use this resource, the requesting Service Account or API Key must have the Project Owner role or Project Access Manager role.

        Parameters
        ----------
        group_id : str
            Unique 24-hexadecimal digit string that identifies your project. Use the [/groups](#tag/Projects/operation/listProjects) endpoint to retrieve all projects to which the authenticated user has access.

            **NOTE**: Groups and projects are synonymous terms. Your group id is the same as your project id. For existing groups, your group/project id remains the same. The resource and corresponding endpoints use the term groups.

        api_user_id : str
            Unique 24-hexadecimal digit string that identifies this organization API key that you want to unassign from one project.

        page_num : typing.Optional[int]
            Number of the page that displays the current set of the total objects that the response returns.

        items_per_page : typing.Optional[int]
            Number of items that the response returns per page.

        include_count : typing.Optional[bool]
            Flag that indicates whether the response returns the total number of items (`totalCount`) in the response.

        desc : typing.Optional[str]
            Purpose or explanation provided when someone creates this project API key.

        roles : typing.Optional[typing.Sequence[str]]
            List of roles to grant this API key. If you provide this list, provide a minimum of one role and ensure each role applies to this project.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ApiKeyUserDetails
            OK

        Examples
        --------
        import asyncio

        from atlas_sdk import AsyncAtlasClient

        client = AsyncAtlasClient(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.programmatic_api_keys.update_api_key_roles(
                group_id="32b6e34b3d91647abb20e7b8",
                api_user_id="apiUserId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update_api_key_roles(
            group_id,
            api_user_id,
            page_num=page_num,
            items_per_page=items_per_page,
            include_count=include_count,
            desc=desc,
            roles=roles,
            request_options=request_options,
        )
        return _response.data

    async def list_org_api_keys(
        self,
        org_id: str,
        *,
        include_count: typing.Optional[bool] = None,
        items_per_page: typing.Optional[int] = None,
        page_num: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PaginatedApiApiUser:
        """
        Returns all organization API keys for the specified organization. The organization API keys grant programmatic access to an organization. You can't use the API key to log into MongoDB Cloud through the console. To use this resource, the requesting Service Account or API Key must have the Organization Member role.

        Parameters
        ----------
        org_id : str
            Unique 24-hexadecimal digit string that identifies the organization that contains your projects. Use the [`/orgs`](#tag/Organizations/operation/listOrganizations) endpoint to retrieve all organizations to which the authenticated user has access.

        include_count : typing.Optional[bool]
            Flag that indicates whether the response returns the total number of items (`totalCount`) in the response.

        items_per_page : typing.Optional[int]
            Number of items that the response returns per page.

        page_num : typing.Optional[int]
            Number of the page that displays the current set of the total objects that the response returns.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PaginatedApiApiUser
            OK

        Examples
        --------
        import asyncio

        from atlas_sdk import AsyncAtlasClient

        client = AsyncAtlasClient(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.programmatic_api_keys.list_org_api_keys(
                org_id="4888442a3354817a7320eb61",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list_org_api_keys(
            org_id,
            include_count=include_count,
            items_per_page=items_per_page,
            page_num=page_num,
            request_options=request_options,
        )
        return _response.data

    async def create_org_api_key(
        self,
        org_id: str,
        *,
        desc: str,
        roles: typing.Sequence[str],
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ApiKeyUserDetails:
        """
        Creates one API key for the specified organization. An organization API key grants programmatic access to an organization. You can't use the API key to log into the console. To use this resource, the requesting Service Account or API Key must have the Organization Owner role.

        Parameters
        ----------
        org_id : str
            Unique 24-hexadecimal digit string that identifies the organization that contains your projects. Use the [`/orgs`](#tag/Organizations/operation/listOrganizations) endpoint to retrieve all organizations to which the authenticated user has access.

        desc : str
            Purpose or explanation provided when someone created this organization API key.

        roles : typing.Sequence[str]
            List of roles to grant this API key. If you provide this list, provide a minimum of one role and ensure each role applies to this organization.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ApiKeyUserDetails
            OK

        Examples
        --------
        import asyncio

        from atlas_sdk import AsyncAtlasClient

        client = AsyncAtlasClient(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.programmatic_api_keys.create_org_api_key(
                org_id="4888442a3354817a7320eb61",
                desc="desc",
                roles=["roles"],
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_org_api_key(
            org_id, desc=desc, roles=roles, request_options=request_options
        )
        return _response.data

    async def get_org_api_key(
        self, org_id: str, api_user_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> ApiKeyUserDetails:
        """
        Returns one organization API key. The organization API keys grant programmatic access to an organization. You can't use the API key to log into MongoDB Cloud through the user interface. To use this resource, the requesting Service Account or API Key must have the  Organization Member role.

        Parameters
        ----------
        org_id : str
            Unique 24-hexadecimal digit string that identifies the organization that contains your projects. Use the [`/orgs`](#tag/Organizations/operation/listOrganizations) endpoint to retrieve all organizations to which the authenticated user has access.

        api_user_id : str
            Unique 24-hexadecimal digit string that identifies this organization API key that  you want to update.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ApiKeyUserDetails
            OK

        Examples
        --------
        import asyncio

        from atlas_sdk import AsyncAtlasClient

        client = AsyncAtlasClient(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.programmatic_api_keys.get_org_api_key(
                org_id="4888442a3354817a7320eb61",
                api_user_id="apiUserId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_org_api_key(org_id, api_user_id, request_options=request_options)
        return _response.data

    async def delete_org_api_key(
        self, org_id: str, api_user_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Any:
        """
        Removes one organization API key from the specified organization. When you remove an API key from an organization, MongoDB Cloud also removes that key from any projects that use that key. To use this resource, the requesting Service Account or API Key must have the Organization Owner role.

        Parameters
        ----------
        org_id : str
            Unique 24-hexadecimal digit string that identifies the organization that contains your projects. Use the [`/orgs`](#tag/Organizations/operation/listOrganizations) endpoint to retrieve all organizations to which the authenticated user has access.

        api_user_id : str
            Unique 24-hexadecimal digit string that identifies this organization API key.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Any
            This endpoint does not return a response body.

        Examples
        --------
        import asyncio

        from atlas_sdk import AsyncAtlasClient

        client = AsyncAtlasClient(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.programmatic_api_keys.delete_org_api_key(
                org_id="4888442a3354817a7320eb61",
                api_user_id="apiUserId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete_org_api_key(org_id, api_user_id, request_options=request_options)
        return _response.data

    async def update_org_api_key(
        self,
        org_id: str,
        api_user_id: str,
        *,
        desc: typing.Optional[str] = OMIT,
        roles: typing.Optional[typing.Sequence[str]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ApiKeyUserDetails:
        """
        Updates one organization API key in the specified organization. The organization API keys  grant programmatic access to an organization. To use this resource, the requesting  API Key must have the Organization Owner role.

        Parameters
        ----------
        org_id : str
            Unique 24-hexadecimal digit string that identifies the organization that contains your projects. Use the [`/orgs`](#tag/Organizations/operation/listOrganizations) endpoint to retrieve all organizations to which the authenticated user has access.

        api_user_id : str
            Unique 24-hexadecimal digit string that identifies this organization API key you  want to update.

        desc : typing.Optional[str]
            Purpose or explanation provided when someone creates this organization API key.

        roles : typing.Optional[typing.Sequence[str]]
            List of roles to grant this API key. If you provide this list, provide a minimum of one role and ensure each role applies to this organization.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ApiKeyUserDetails
            OK

        Examples
        --------
        import asyncio

        from atlas_sdk import AsyncAtlasClient

        client = AsyncAtlasClient(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.programmatic_api_keys.update_org_api_key(
                org_id="4888442a3354817a7320eb61",
                api_user_id="apiUserId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update_org_api_key(
            org_id, api_user_id, desc=desc, roles=roles, request_options=request_options
        )
        return _response.data

    async def list_org_access_entries(
        self,
        org_id: str,
        api_user_id: str,
        *,
        include_count: typing.Optional[bool] = None,
        items_per_page: typing.Optional[int] = None,
        page_num: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PaginatedApiUserAccessListResponse:
        """
        Returns all access list entries that you configured for the specified organization API key. To use this resource, the requesting Service Account or API Key must have the Organization Member role.

        Parameters
        ----------
        org_id : str
            Unique 24-hexadecimal digit string that identifies the organization that contains your projects. Use the [`/orgs`](#tag/Organizations/operation/listOrganizations) endpoint to retrieve all organizations to which the authenticated user has access.

        api_user_id : str
            Unique 24-hexadecimal digit string that identifies this organization API key for which you want to return access list entries.

        include_count : typing.Optional[bool]
            Flag that indicates whether the response returns the total number of items (`totalCount`) in the response.

        items_per_page : typing.Optional[int]
            Number of items that the response returns per page.

        page_num : typing.Optional[int]
            Number of the page that displays the current set of the total objects that the response returns.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PaginatedApiUserAccessListResponse
            OK

        Examples
        --------
        import asyncio

        from atlas_sdk import AsyncAtlasClient

        client = AsyncAtlasClient(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.programmatic_api_keys.list_org_access_entries(
                org_id="4888442a3354817a7320eb61",
                api_user_id="apiUserId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list_org_access_entries(
            org_id,
            api_user_id,
            include_count=include_count,
            items_per_page=items_per_page,
            page_num=page_num,
            request_options=request_options,
        )
        return _response.data

    async def create_org_access_entry(
        self,
        org_id: str,
        api_user_id: str,
        *,
        request: typing.Sequence[UserAccessListRequest],
        include_count: typing.Optional[bool] = None,
        items_per_page: typing.Optional[int] = None,
        page_num: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PaginatedApiUserAccessListResponse:
        """
        Creates the access list entries for the specified organization API key. Resources require all API requests originate from IP addresses on the API access list. To use this resource, the requesting Service Account or API Key must have the Read Write role.

        Parameters
        ----------
        org_id : str
            Unique 24-hexadecimal digit string that identifies the organization that contains your projects. Use the [`/orgs`](#tag/Organizations/operation/listOrganizations) endpoint to retrieve all organizations to which the authenticated user has access.

        api_user_id : str
            Unique 24-hexadecimal digit string that identifies this organization API key for which you want to create a new access list entry.

        request : typing.Sequence[UserAccessListRequest]

        include_count : typing.Optional[bool]
            Flag that indicates whether the response returns the total number of items (`totalCount`) in the response.

        items_per_page : typing.Optional[int]
            Number of items that the response returns per page.

        page_num : typing.Optional[int]
            Number of the page that displays the current set of the total objects that the response returns.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PaginatedApiUserAccessListResponse
            OK

        Examples
        --------
        import asyncio

        from atlas_sdk import AsyncAtlasClient, UserAccessListRequest

        client = AsyncAtlasClient(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.programmatic_api_keys.create_org_access_entry(
                org_id="4888442a3354817a7320eb61",
                api_user_id="apiUserId",
                request=[UserAccessListRequest()],
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_org_access_entry(
            org_id,
            api_user_id,
            request=request,
            include_count=include_count,
            items_per_page=items_per_page,
            page_num=page_num,
            request_options=request_options,
        )
        return _response.data

    async def get_org_access_entry(
        self, org_id: str, api_user_id: str, ip_address: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> UserAccessListResponse:
        """
        Returns one access list entry for the specified organization API key. Resources require  all API requests originate from IP addresses on the API access list. To use this resource, the requesting Service Account or API Key must have the Organization Member role.

        Parameters
        ----------
        org_id : str
            Unique 24-hexadecimal digit string that identifies the organization that contains your projects. Use the [`/orgs`](#tag/Organizations/operation/listOrganizations) endpoint to retrieve all organizations to which the authenticated user has access.

        api_user_id : str
            Unique 24-hexadecimal digit string that identifies this organization API key for  which you want to return access list entries.

        ip_address : str
            One IP address or multiple IP addresses represented as one CIDR block to limit  requests to API resources in the specified organization. When adding a CIDR block with a subnet mask, such as  192.0.2.0/24, use the URL-encoded value %2F for the forward slash /.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        UserAccessListResponse
            OK

        Examples
        --------
        import asyncio

        from atlas_sdk import AsyncAtlasClient

        client = AsyncAtlasClient(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.programmatic_api_keys.get_org_access_entry(
                org_id="4888442a3354817a7320eb61",
                api_user_id="apiUserId",
                ip_address="192.0.2.0%2F24",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_org_access_entry(
            org_id, api_user_id, ip_address, request_options=request_options
        )
        return _response.data

    async def delete_access_entry(
        self, org_id: str, api_user_id: str, ip_address: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Any:
        """
        Removes the specified access list entry from the specified organization API key. Resources require all API requests originate from the IP addresses on the API access list. To use this resource, the requesting Service Account or API Key must have the Read Write role. In addition, you cannot remove the requesting IP address from the requesting organization API key.

        Parameters
        ----------
        org_id : str
            Unique 24-hexadecimal digit string that identifies the organization that contains your projects. Use the [`/orgs`](#tag/Organizations/operation/listOrganizations) endpoint to retrieve all organizations to which the authenticated user has access.

        api_user_id : str
            Unique 24-hexadecimal digit string that identifies this organization API key for which you want to remove access list entries.

        ip_address : str
            One IP address or multiple IP addresses represented as one CIDR block to limit requests to API resources in the specified organization. When adding a CIDR block with a subnet mask, such as 192.0.2.0/24, use the URL-encoded value %2F for the forward slash /.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Any
            This endpoint does not return a response body.

        Examples
        --------
        import asyncio

        from atlas_sdk import AsyncAtlasClient

        client = AsyncAtlasClient(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.programmatic_api_keys.delete_access_entry(
                org_id="4888442a3354817a7320eb61",
                api_user_id="apiUserId",
                ip_address="192.0.2.0%2F24",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete_access_entry(
            org_id, api_user_id, ip_address, request_options=request_options
        )
        return _response.data
