# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.data_federation_tenant_query_limit import DataFederationTenantQueryLimit
from ..types.data_lake_cloud_provider_config import DataLakeCloudProviderConfig
from ..types.data_lake_data_process_region import DataLakeDataProcessRegion
from ..types.data_lake_storage import DataLakeStorage
from ..types.data_lake_tenant import DataLakeTenant
from ..types.paginated_private_network_endpoint_id_entry import PaginatedPrivateNetworkEndpointIdEntry
from ..types.private_endpoint_hostname import PrivateEndpointHostname
from ..types.private_network_endpoint_id_entry import PrivateNetworkEndpointIdEntry
from .raw_client import AsyncRawDataFederationClient, RawDataFederationClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class DataFederationClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawDataFederationClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawDataFederationClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawDataFederationClient
        """
        return self._raw_client

    def list_data_federation(
        self,
        group_id: str,
        *,
        type: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.List[DataLakeTenant]:
        """
        Returns the details of all federated database instances in the specified project. To use this resource, the requesting Service Account or API Key must have the Project Read Only or higher role.

        Parameters
        ----------
        group_id : str
            Unique 24-hexadecimal digit string that identifies your project. Use the [/groups](#tag/Projects/operation/listProjects) endpoint to retrieve all projects to which the authenticated user has access.

            **NOTE**: Groups and projects are synonymous terms. Your group id is the same as your project id. For existing groups, your group/project id remains the same. The resource and corresponding endpoints use the term groups.

        type : typing.Optional[str]
            Type of Federated Database Instances to return.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[DataLakeTenant]
            OK

        Examples
        --------
        from atlas_sdk import AtlasClient

        client = AtlasClient(
            token="YOUR_TOKEN",
        )
        client.data_federation.list_data_federation(
            group_id="32b6e34b3d91647abb20e7b8",
        )
        """
        _response = self._raw_client.list_data_federation(group_id, type=type, request_options=request_options)
        return _response.data

    def create_data_federation(
        self,
        group_id_: str,
        *,
        skip_role_validation: typing.Optional[bool] = None,
        cloud_provider_config: typing.Optional[DataLakeCloudProviderConfig] = OMIT,
        data_process_region: typing.Optional[DataLakeDataProcessRegion] = OMIT,
        group_id: typing.Optional[str] = OMIT,
        hostnames: typing.Optional[typing.Sequence[str]] = OMIT,
        name: typing.Optional[str] = OMIT,
        private_endpoint_hostnames: typing.Optional[typing.Sequence[PrivateEndpointHostname]] = OMIT,
        state: typing.Optional[str] = OMIT,
        storage: typing.Optional[DataLakeStorage] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> DataLakeTenant:
        """
        Creates one federated database instance in the specified project. To use this resource, the requesting Service Account or API Key must have the Project Owner or Project Charts Admin roles.

        Parameters
        ----------
        group_id_ : str
            Unique 24-hexadecimal digit string that identifies your project. Use the [/groups](#tag/Projects/operation/listProjects) endpoint to retrieve all projects to which the authenticated user has access.

            **NOTE**: Groups and projects are synonymous terms. Your group id is the same as your project id. For existing groups, your group/project id remains the same. The resource and corresponding endpoints use the term groups.

        skip_role_validation : typing.Optional[bool]
            Flag that indicates whether this request should check if the requesting IAM role can read from the S3 bucket. AWS checks if the role can list the objects in the bucket before writing to it. Some IAM roles only need write permissions. This flag allows you to skip that check.

        cloud_provider_config : typing.Optional[DataLakeCloudProviderConfig]

        data_process_region : typing.Optional[DataLakeDataProcessRegion]

        group_id : typing.Optional[str]
            Unique 24-hexadecimal character string that identifies the project.

        hostnames : typing.Optional[typing.Sequence[str]]
            List that contains the hostnames assigned to the Federated Database Instance.

        name : typing.Optional[str]
            Human-readable label that identifies the Federated Database Instance.

        private_endpoint_hostnames : typing.Optional[typing.Sequence[PrivateEndpointHostname]]
            List that contains the sets of private endpoints and hostnames.

        state : typing.Optional[str]
            Label that indicates the status of the Federated Database Instance.

        storage : typing.Optional[DataLakeStorage]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DataLakeTenant
            OK

        Examples
        --------
        from atlas_sdk import AtlasClient

        client = AtlasClient(
            token="YOUR_TOKEN",
        )
        client.data_federation.create_data_federation(
            group_id_="32b6e34b3d91647abb20e7b8",
        )
        """
        _response = self._raw_client.create_data_federation(
            group_id_,
            skip_role_validation=skip_role_validation,
            cloud_provider_config=cloud_provider_config,
            data_process_region=data_process_region,
            group_id=group_id,
            hostnames=hostnames,
            name=name,
            private_endpoint_hostnames=private_endpoint_hostnames,
            state=state,
            storage=storage,
            request_options=request_options,
        )
        return _response.data

    def get_data_federation(
        self, group_id: str, tenant_name: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> DataLakeTenant:
        """
        Returns the details of one federated database instance within the specified project. To use this resource, the requesting Service Account or API Key must have the Project Read Only or Project Charts Admin roles.

        Parameters
        ----------
        group_id : str
            Unique 24-hexadecimal digit string that identifies your project. Use the [/groups](#tag/Projects/operation/listProjects) endpoint to retrieve all projects to which the authenticated user has access.

            **NOTE**: Groups and projects are synonymous terms. Your group id is the same as your project id. For existing groups, your group/project id remains the same. The resource and corresponding endpoints use the term groups.

        tenant_name : str
            Human-readable label that identifies the Federated Database to return.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DataLakeTenant
            OK

        Examples
        --------
        from atlas_sdk import AtlasClient

        client = AtlasClient(
            token="YOUR_TOKEN",
        )
        client.data_federation.get_data_federation(
            group_id="32b6e34b3d91647abb20e7b8",
            tenant_name="tenantName",
        )
        """
        _response = self._raw_client.get_data_federation(group_id, tenant_name, request_options=request_options)
        return _response.data

    def delete_data_federation(
        self, group_id: str, tenant_name: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Any:
        """
        Removes one federated database instance from the specified project. To use this resource, the requesting Service Account or API Key must have the Project Owner or Project Charts Admin roles.

        Parameters
        ----------
        group_id : str
            Unique 24-hexadecimal digit string that identifies your project. Use the [/groups](#tag/Projects/operation/listProjects) endpoint to retrieve all projects to which the authenticated user has access.

            **NOTE**: Groups and projects are synonymous terms. Your group id is the same as your project id. For existing groups, your group/project id remains the same. The resource and corresponding endpoints use the term groups.

        tenant_name : str
            Human-readable label that identifies the federated database instance to remove.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Any
            This endpoint does not return a response body.

        Examples
        --------
        from atlas_sdk import AtlasClient

        client = AtlasClient(
            token="YOUR_TOKEN",
        )
        client.data_federation.delete_data_federation(
            group_id="32b6e34b3d91647abb20e7b8",
            tenant_name="tenantName",
        )
        """
        _response = self._raw_client.delete_data_federation(group_id, tenant_name, request_options=request_options)
        return _response.data

    def update_data_federation(
        self,
        group_id_: str,
        tenant_name: str,
        *,
        skip_role_validation: bool,
        cloud_provider_config: typing.Optional[DataLakeCloudProviderConfig] = OMIT,
        data_process_region: typing.Optional[DataLakeDataProcessRegion] = OMIT,
        group_id: typing.Optional[str] = OMIT,
        hostnames: typing.Optional[typing.Sequence[str]] = OMIT,
        name: typing.Optional[str] = OMIT,
        private_endpoint_hostnames: typing.Optional[typing.Sequence[PrivateEndpointHostname]] = OMIT,
        state: typing.Optional[str] = OMIT,
        storage: typing.Optional[DataLakeStorage] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> DataLakeTenant:
        """
        Updates the details of one federated database instance in the specified project. To use this resource, the requesting Service Account or API Key must have the Project Owner or higher role.

        Parameters
        ----------
        group_id_ : str
            Unique 24-hexadecimal digit string that identifies your project. Use the [/groups](#tag/Projects/operation/listProjects) endpoint to retrieve all projects to which the authenticated user has access.

            **NOTE**: Groups and projects are synonymous terms. Your group id is the same as your project id. For existing groups, your group/project id remains the same. The resource and corresponding endpoints use the term groups.

        tenant_name : str
            Human-readable label that identifies the federated database instance to update.

        skip_role_validation : bool
            Flag that indicates whether this request should check if the requesting IAM role can read from the S3 bucket. AWS checks if the role can list the objects in the bucket before writing to it. Some IAM roles only need write permissions. This flag allows you to skip that check.

        cloud_provider_config : typing.Optional[DataLakeCloudProviderConfig]

        data_process_region : typing.Optional[DataLakeDataProcessRegion]

        group_id : typing.Optional[str]
            Unique 24-hexadecimal character string that identifies the project.

        hostnames : typing.Optional[typing.Sequence[str]]
            List that contains the hostnames assigned to the Federated Database Instance.

        name : typing.Optional[str]
            Human-readable label that identifies the Federated Database Instance.

        private_endpoint_hostnames : typing.Optional[typing.Sequence[PrivateEndpointHostname]]
            List that contains the sets of private endpoints and hostnames.

        state : typing.Optional[str]
            Label that indicates the status of the Federated Database Instance.

        storage : typing.Optional[DataLakeStorage]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DataLakeTenant
            OK

        Examples
        --------
        from atlas_sdk import AtlasClient

        client = AtlasClient(
            token="YOUR_TOKEN",
        )
        client.data_federation.update_data_federation(
            group_id_="32b6e34b3d91647abb20e7b8",
            tenant_name="tenantName",
            skip_role_validation=True,
        )
        """
        _response = self._raw_client.update_data_federation(
            group_id_,
            tenant_name,
            skip_role_validation=skip_role_validation,
            cloud_provider_config=cloud_provider_config,
            data_process_region=data_process_region,
            group_id=group_id,
            hostnames=hostnames,
            name=name,
            private_endpoint_hostnames=private_endpoint_hostnames,
            state=state,
            storage=storage,
            request_options=request_options,
        )
        return _response.data

    def list_data_federation_limits(
        self, group_id: str, tenant_name: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.List[DataFederationTenantQueryLimit]:
        """
        Returns query limits for a federated databases instance in the specified project. To use this resource, the requesting Service Account or API Key must have the Project Read Only role.

        Parameters
        ----------
        group_id : str
            Unique 24-hexadecimal digit string that identifies your project. Use the [/groups](#tag/Projects/operation/listProjects) endpoint to retrieve all projects to which the authenticated user has access.

            **NOTE**: Groups and projects are synonymous terms. Your group id is the same as your project id. For existing groups, your group/project id remains the same. The resource and corresponding endpoints use the term groups.

        tenant_name : str
            Human-readable label that identifies the federated database instance for which you want to retrieve query limits.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[DataFederationTenantQueryLimit]
            OK

        Examples
        --------
        from atlas_sdk import AtlasClient

        client = AtlasClient(
            token="YOUR_TOKEN",
        )
        client.data_federation.list_data_federation_limits(
            group_id="32b6e34b3d91647abb20e7b8",
            tenant_name="tenantName",
        )
        """
        _response = self._raw_client.list_data_federation_limits(group_id, tenant_name, request_options=request_options)
        return _response.data

    def get_data_federation_limit(
        self,
        group_id: str,
        tenant_name: str,
        limit_name: str,
        *,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> DataFederationTenantQueryLimit:
        """
        Returns the details of one query limit for the specified federated database instance in the specified project. To use this resource, the requesting Service Account or API Key must have the Project Read Only role.

        Parameters
        ----------
        group_id : str
            Unique 24-hexadecimal digit string that identifies your project. Use the [/groups](#tag/Projects/operation/listProjects) endpoint to retrieve all projects to which the authenticated user has access.

            **NOTE**: Groups and projects are synonymous terms. Your group id is the same as your project id. For existing groups, your group/project id remains the same. The resource and corresponding endpoints use the term groups.

        tenant_name : str
            Human-readable label that identifies the federated database instance to which the query limit applies.

        limit_name : str
            Human-readable label that identifies this data federation instance limit.

            | Limit Name | Description | Default |
            | --- | --- | --- |
            | `bytesProcessed.query` | Limit on the number of bytes processed during a single data federation query | N/A |
            | `bytesProcessed.daily` | Limit on the number of bytes processed for the data federation instance for the current day | N/A |
            | `bytesProcessed.weekly` | Limit on the number of bytes processed for the data federation instance for the current week | N/A |
            | `bytesProcessed.monthly` | Limit on the number of bytes processed for the data federation instance for the current month | N/A |

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DataFederationTenantQueryLimit
            OK

        Examples
        --------
        from atlas_sdk import AtlasClient

        client = AtlasClient(
            token="YOUR_TOKEN",
        )
        client.data_federation.get_data_federation_limit(
            group_id="32b6e34b3d91647abb20e7b8",
            tenant_name="tenantName",
            limit_name="limitName",
        )
        """
        _response = self._raw_client.get_data_federation_limit(
            group_id, tenant_name, limit_name, request_options=request_options
        )
        return _response.data

    def delete_data_federation_limit(
        self,
        group_id: str,
        tenant_name: str,
        limit_name: str,
        *,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.Any:
        """
        Deletes one query limit for one federated database instance. To use this resource, the requesting Service Account or API Key must have the Project Owner role.

        Parameters
        ----------
        group_id : str
            Unique 24-hexadecimal digit string that identifies your project. Use the [/groups](#tag/Projects/operation/listProjects) endpoint to retrieve all projects to which the authenticated user has access.

            **NOTE**: Groups and projects are synonymous terms. Your group id is the same as your project id. For existing groups, your group/project id remains the same. The resource and corresponding endpoints use the term groups.

        tenant_name : str
            Human-readable label that identifies the federated database instance to which the query limit applies.

        limit_name : str
            Human-readable label that identifies this data federation instance limit.

            | Limit Name | Description | Default |
            | --- | --- | --- |
            | `bytesProcessed.query` | Limit on the number of bytes processed during a single data federation query | N/A |
            | `bytesProcessed.daily` | Limit on the number of bytes processed for the data federation instance for the current day | N/A |
            | `bytesProcessed.weekly` | Limit on the number of bytes processed for the data federation instance for the current week | N/A |
            | `bytesProcessed.monthly` | Limit on the number of bytes processed for the data federation instance for the current month | N/A |

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Any
            This endpoint does not return a response body.

        Examples
        --------
        from atlas_sdk import AtlasClient

        client = AtlasClient(
            token="YOUR_TOKEN",
        )
        client.data_federation.delete_data_federation_limit(
            group_id="32b6e34b3d91647abb20e7b8",
            tenant_name="tenantName",
            limit_name="limitName",
        )
        """
        _response = self._raw_client.delete_data_federation_limit(
            group_id, tenant_name, limit_name, request_options=request_options
        )
        return _response.data

    def set_data_federation_limit(
        self,
        group_id: str,
        tenant_name_: str,
        limit_name: str,
        *,
        value: int,
        current_usage: typing.Optional[int] = OMIT,
        default_limit: typing.Optional[int] = OMIT,
        last_modified_date: typing.Optional[dt.datetime] = OMIT,
        maximum_limit: typing.Optional[int] = OMIT,
        name: typing.Optional[str] = OMIT,
        overrun_policy: typing.Optional[str] = OMIT,
        tenant_name: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> DataFederationTenantQueryLimit:
        """
        Creates or updates one query limit for one federated database instance. To use this resource, the requesting Service Account or API Key must have the Project Owner role.

        Parameters
        ----------
        group_id : str
            Unique 24-hexadecimal digit string that identifies your project. Use the [/groups](#tag/Projects/operation/listProjects) endpoint to retrieve all projects to which the authenticated user has access.

            **NOTE**: Groups and projects are synonymous terms. Your group id is the same as your project id. For existing groups, your group/project id remains the same. The resource and corresponding endpoints use the term groups.

        tenant_name_ : str
            Human-readable label that identifies the federated database instance to which the query limit applies.

        limit_name : str
            Human-readable label that identifies this data federation instance limit.

            | Limit Name | Description | Default |
            | --- | --- | --- |
            | `bytesProcessed.query` | Limit on the number of bytes processed during a single data federation query | N/A |
            | `bytesProcessed.daily` | Limit on the number of bytes processed for the data federation instance for the current day | N/A |
            | `bytesProcessed.weekly` | Limit on the number of bytes processed for the data federation instance for the current week | N/A |
            | `bytesProcessed.monthly` | Limit on the number of bytes processed for the data federation instance for the current month | N/A |

        value : int
            Amount to set the limit to.

        current_usage : typing.Optional[int]
            Amount that indicates the current usage of the limit.

        default_limit : typing.Optional[int]
            Default value of the limit.

        last_modified_date : typing.Optional[dt.datetime]
            Only used for Data Federation limits. Timestamp that indicates when this usage limit was last modified. This field uses the ISO 8601 timestamp format in UTC.

        maximum_limit : typing.Optional[int]
            Maximum value of the limit.

        name : typing.Optional[str]
            Human-readable label that identifies the user-managed limit to modify.

        overrun_policy : typing.Optional[str]
            Only used for Data Federation limits. Action to take when the usage limit is exceeded. If limit span is set to QUERY, this is ignored because MongoDB Cloud stops the query when it exceeds the usage limit.

        tenant_name : typing.Optional[str]
            Human-readable label that identifies the Federated Database Instance. If specified, the usage limit is for the specified federated database instance only. If omitted, the usage limit is for all federated database instances in the project.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DataFederationTenantQueryLimit
            OK

        Examples
        --------
        from atlas_sdk import AtlasClient

        client = AtlasClient(
            token="YOUR_TOKEN",
        )
        client.data_federation.set_data_federation_limit(
            group_id="32b6e34b3d91647abb20e7b8",
            tenant_name_="tenantName",
            limit_name="limitName",
            value=1000000,
        )
        """
        _response = self._raw_client.set_data_federation_limit(
            group_id,
            tenant_name_,
            limit_name,
            value=value,
            current_usage=current_usage,
            default_limit=default_limit,
            last_modified_date=last_modified_date,
            maximum_limit=maximum_limit,
            name=name,
            overrun_policy=overrun_policy,
            tenant_name=tenant_name,
            request_options=request_options,
        )
        return _response.data

    def download_federation_query_logs(
        self,
        group_id: str,
        tenant_name: str,
        *,
        end_date: typing.Optional[int] = None,
        start_date: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.Iterator[bytes]:
        """
        Downloads the query logs for the specified federated database instance. To use this resource, the requesting Service Account or API Key must have the Project Owner or Project Data Access Read Write roles. The API does not support direct calls with the json response schema. You must request a gzip response schema using an accept header of the format: `Accept: application/vnd.atlas.YYYY-MM-DD+gzip`.

        Parameters
        ----------
        group_id : str
            Unique 24-hexadecimal digit string that identifies your project. Use the [/groups](#tag/Projects/operation/listProjects) endpoint to retrieve all projects to which the authenticated user has access.

            **NOTE**: Groups and projects are synonymous terms. Your group id is the same as your project id. For existing groups, your group/project id remains the same. The resource and corresponding endpoints use the term groups.

        tenant_name : str
            Human-readable label that identifies the federated database instance for which you want to download query logs.

        end_date : typing.Optional[int]
            Timestamp that specifies the end point for the range of log messages to download.  MongoDB Cloud expresses this timestamp in the number of seconds that have elapsed since the UNIX epoch.

        start_date : typing.Optional[int]
            Timestamp that specifies the starting point for the range of log messages to download. MongoDB Cloud expresses this timestamp in the number of seconds that have elapsed since the UNIX epoch.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration. You can pass in configuration such as `chunk_size`, and more to customize the request and response.

        Returns
        -------
        typing.Iterator[bytes]
            OK

        Examples
        --------
        from atlas_sdk import AtlasClient

        client = AtlasClient(
            token="YOUR_TOKEN",
        )
        client.data_federation.download_federation_query_logs()
        """
        with self._raw_client.download_federation_query_logs(
            group_id, tenant_name, end_date=end_date, start_date=start_date, request_options=request_options
        ) as r:
            yield from r.data

    def list_private_endpoint_ids(
        self,
        group_id: str,
        *,
        include_count: typing.Optional[bool] = None,
        items_per_page: typing.Optional[int] = None,
        page_num: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PaginatedPrivateNetworkEndpointIdEntry:
        """
        Returns all private endpoints for Federated Database Instances and Online Archives in the specified project. To use this resource, the requesting Service Account or API Key must have the Project Read Only or Project Charts Admin roles.

        Parameters
        ----------
        group_id : str
            Unique 24-hexadecimal digit string that identifies your project. Use the [/groups](#tag/Projects/operation/listProjects) endpoint to retrieve all projects to which the authenticated user has access.

            **NOTE**: Groups and projects are synonymous terms. Your group id is the same as your project id. For existing groups, your group/project id remains the same. The resource and corresponding endpoints use the term groups.

        include_count : typing.Optional[bool]
            Flag that indicates whether the response returns the total number of items (`totalCount`) in the response.

        items_per_page : typing.Optional[int]
            Number of items that the response returns per page.

        page_num : typing.Optional[int]
            Number of the page that displays the current set of the total objects that the response returns.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PaginatedPrivateNetworkEndpointIdEntry
            OK

        Examples
        --------
        from atlas_sdk import AtlasClient

        client = AtlasClient(
            token="YOUR_TOKEN",
        )
        client.data_federation.list_private_endpoint_ids(
            group_id="32b6e34b3d91647abb20e7b8",
        )
        """
        _response = self._raw_client.list_private_endpoint_ids(
            group_id,
            include_count=include_count,
            items_per_page=items_per_page,
            page_num=page_num,
            request_options=request_options,
        )
        return _response.data

    def create_private_endpoint_id(
        self,
        group_id: str,
        *,
        endpoint_id: str,
        azure_link_id: typing.Optional[str] = OMIT,
        comment: typing.Optional[str] = OMIT,
        customer_endpoint_dns_name: typing.Optional[str] = OMIT,
        customer_endpoint_ip_address: typing.Optional[str] = OMIT,
        error_message: typing.Optional[str] = OMIT,
        provider: typing.Optional[str] = OMIT,
        region: typing.Optional[str] = OMIT,
        status: typing.Optional[str] = OMIT,
        type: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PaginatedPrivateNetworkEndpointIdEntry:
        """
        Adds one private endpoint for Federated Database Instances and Online Archives to the specified projects. If the endpoint ID already exists and the associated comment is unchanged, Atlas Data Federation makes no change to the endpoint ID list. If the endpoint ID already exists and the associated comment is changed, Atlas Data Federation updates the comment value only in the endpoint ID list. If the endpoint ID doesn't exist, Atlas Data Federation appends the new endpoint to the list of endpoints in the endpoint ID list. Each region has an associated service name for the various endpoints. For the latest list of supported regions and their service names, see the external documentation. To use this resource, the requesting Service Account or API Key must have the Project Owner or Project Charts Admin roles.

        Parameters
        ----------
        group_id : str
            Unique 24-hexadecimal digit string that identifies your project. Use the [/groups](#tag/Projects/operation/listProjects) endpoint to retrieve all projects to which the authenticated user has access.

            **NOTE**: Groups and projects are synonymous terms. Your group id is the same as your project id. For existing groups, your group/project id remains the same. The resource and corresponding endpoints use the term groups.

        endpoint_id : str
            Unique 22-character alphanumeric string that identifies the private endpoint.

        azure_link_id : typing.Optional[str]
            Link ID that identifies the Azure private endpoint connection.

        comment : typing.Optional[str]
            Human-readable string to associate with this private endpoint.

        customer_endpoint_dns_name : typing.Optional[str]
            Human-readable label to identify customer's VPC endpoint DNS name. If defined, you must also specify a value for `region`.

        customer_endpoint_ip_address : typing.Optional[str]
            IP address used to connect to the Azure private endpoint.

        error_message : typing.Optional[str]
            Error message describing a failure approving the private endpoint request.

        provider : typing.Optional[str]
            Human-readable label that identifies the cloud service provider. Atlas Data Lake supports Amazon Web Services only.

        region : typing.Optional[str]
            Human-readable label to identify the region of customer's VPC endpoint. If defined, you must also specify a value for `customerEndpointDNSName`.

        status : typing.Optional[str]
            Status of the private endpoint connection request.

        type : typing.Optional[str]
            Human-readable label that identifies the resource type associated with this private endpoint.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PaginatedPrivateNetworkEndpointIdEntry
            OK

        Examples
        --------
        from atlas_sdk import AtlasClient

        client = AtlasClient(
            token="YOUR_TOKEN",
        )
        client.data_federation.create_private_endpoint_id(
            group_id="32b6e34b3d91647abb20e7b8",
            endpoint_id="vpce-3bf78b0ddee411ba1",
        )
        """
        _response = self._raw_client.create_private_endpoint_id(
            group_id,
            endpoint_id=endpoint_id,
            azure_link_id=azure_link_id,
            comment=comment,
            customer_endpoint_dns_name=customer_endpoint_dns_name,
            customer_endpoint_ip_address=customer_endpoint_ip_address,
            error_message=error_message,
            provider=provider,
            region=region,
            status=status,
            type=type,
            request_options=request_options,
        )
        return _response.data

    def get_private_endpoint_id(
        self, group_id: str, endpoint_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> PrivateNetworkEndpointIdEntry:
        """
        Returns the specified private endpoint for Federated Database Instances or Online Archives in the specified project. To use this resource, the requesting Service Account or API Key must have the Project Read Only or Project Charts Admin roles.

        Parameters
        ----------
        group_id : str
            Unique 24-hexadecimal digit string that identifies your project. Use the [/groups](#tag/Projects/operation/listProjects) endpoint to retrieve all projects to which the authenticated user has access.

            **NOTE**: Groups and projects are synonymous terms. Your group id is the same as your project id. For existing groups, your group/project id remains the same. The resource and corresponding endpoints use the term groups.

        endpoint_id : str
            Unique 22-character alphanumeric string that identifies the private endpoint to return. Atlas Data Federation supports AWS private endpoints using the AWS PrivateLink feature.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PrivateNetworkEndpointIdEntry
            OK

        Examples
        --------
        from atlas_sdk import AtlasClient

        client = AtlasClient(
            token="YOUR_TOKEN",
        )
        client.data_federation.get_private_endpoint_id(
            group_id="32b6e34b3d91647abb20e7b8",
            endpoint_id="endpointId",
        )
        """
        _response = self._raw_client.get_private_endpoint_id(group_id, endpoint_id, request_options=request_options)
        return _response.data

    def delete_private_endpoint_id(
        self, group_id: str, endpoint_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Any:
        """
        Removes one private endpoint for Federated Database Instances and Online Archives in the specified project. To use this resource, the requesting Service Account or API Key must have the Project Owner role.

        Parameters
        ----------
        group_id : str
            Unique 24-hexadecimal digit string that identifies your project. Use the [/groups](#tag/Projects/operation/listProjects) endpoint to retrieve all projects to which the authenticated user has access.

            **NOTE**: Groups and projects are synonymous terms. Your group id is the same as your project id. For existing groups, your group/project id remains the same. The resource and corresponding endpoints use the term groups.

        endpoint_id : str
            Unique 22-character alphanumeric string that identifies the private endpoint to remove. Atlas Data Federation supports AWS private endpoints using the AWS PrivateLink feature.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Any
            This endpoint does not return a response body.

        Examples
        --------
        from atlas_sdk import AtlasClient

        client = AtlasClient(
            token="YOUR_TOKEN",
        )
        client.data_federation.delete_private_endpoint_id(
            group_id="32b6e34b3d91647abb20e7b8",
            endpoint_id="endpointId",
        )
        """
        _response = self._raw_client.delete_private_endpoint_id(group_id, endpoint_id, request_options=request_options)
        return _response.data


class AsyncDataFederationClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawDataFederationClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawDataFederationClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawDataFederationClient
        """
        return self._raw_client

    async def list_data_federation(
        self,
        group_id: str,
        *,
        type: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.List[DataLakeTenant]:
        """
        Returns the details of all federated database instances in the specified project. To use this resource, the requesting Service Account or API Key must have the Project Read Only or higher role.

        Parameters
        ----------
        group_id : str
            Unique 24-hexadecimal digit string that identifies your project. Use the [/groups](#tag/Projects/operation/listProjects) endpoint to retrieve all projects to which the authenticated user has access.

            **NOTE**: Groups and projects are synonymous terms. Your group id is the same as your project id. For existing groups, your group/project id remains the same. The resource and corresponding endpoints use the term groups.

        type : typing.Optional[str]
            Type of Federated Database Instances to return.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[DataLakeTenant]
            OK

        Examples
        --------
        import asyncio

        from atlas_sdk import AsyncAtlasClient

        client = AsyncAtlasClient(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.data_federation.list_data_federation(
                group_id="32b6e34b3d91647abb20e7b8",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list_data_federation(group_id, type=type, request_options=request_options)
        return _response.data

    async def create_data_federation(
        self,
        group_id_: str,
        *,
        skip_role_validation: typing.Optional[bool] = None,
        cloud_provider_config: typing.Optional[DataLakeCloudProviderConfig] = OMIT,
        data_process_region: typing.Optional[DataLakeDataProcessRegion] = OMIT,
        group_id: typing.Optional[str] = OMIT,
        hostnames: typing.Optional[typing.Sequence[str]] = OMIT,
        name: typing.Optional[str] = OMIT,
        private_endpoint_hostnames: typing.Optional[typing.Sequence[PrivateEndpointHostname]] = OMIT,
        state: typing.Optional[str] = OMIT,
        storage: typing.Optional[DataLakeStorage] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> DataLakeTenant:
        """
        Creates one federated database instance in the specified project. To use this resource, the requesting Service Account or API Key must have the Project Owner or Project Charts Admin roles.

        Parameters
        ----------
        group_id_ : str
            Unique 24-hexadecimal digit string that identifies your project. Use the [/groups](#tag/Projects/operation/listProjects) endpoint to retrieve all projects to which the authenticated user has access.

            **NOTE**: Groups and projects are synonymous terms. Your group id is the same as your project id. For existing groups, your group/project id remains the same. The resource and corresponding endpoints use the term groups.

        skip_role_validation : typing.Optional[bool]
            Flag that indicates whether this request should check if the requesting IAM role can read from the S3 bucket. AWS checks if the role can list the objects in the bucket before writing to it. Some IAM roles only need write permissions. This flag allows you to skip that check.

        cloud_provider_config : typing.Optional[DataLakeCloudProviderConfig]

        data_process_region : typing.Optional[DataLakeDataProcessRegion]

        group_id : typing.Optional[str]
            Unique 24-hexadecimal character string that identifies the project.

        hostnames : typing.Optional[typing.Sequence[str]]
            List that contains the hostnames assigned to the Federated Database Instance.

        name : typing.Optional[str]
            Human-readable label that identifies the Federated Database Instance.

        private_endpoint_hostnames : typing.Optional[typing.Sequence[PrivateEndpointHostname]]
            List that contains the sets of private endpoints and hostnames.

        state : typing.Optional[str]
            Label that indicates the status of the Federated Database Instance.

        storage : typing.Optional[DataLakeStorage]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DataLakeTenant
            OK

        Examples
        --------
        import asyncio

        from atlas_sdk import AsyncAtlasClient

        client = AsyncAtlasClient(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.data_federation.create_data_federation(
                group_id_="32b6e34b3d91647abb20e7b8",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_data_federation(
            group_id_,
            skip_role_validation=skip_role_validation,
            cloud_provider_config=cloud_provider_config,
            data_process_region=data_process_region,
            group_id=group_id,
            hostnames=hostnames,
            name=name,
            private_endpoint_hostnames=private_endpoint_hostnames,
            state=state,
            storage=storage,
            request_options=request_options,
        )
        return _response.data

    async def get_data_federation(
        self, group_id: str, tenant_name: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> DataLakeTenant:
        """
        Returns the details of one federated database instance within the specified project. To use this resource, the requesting Service Account or API Key must have the Project Read Only or Project Charts Admin roles.

        Parameters
        ----------
        group_id : str
            Unique 24-hexadecimal digit string that identifies your project. Use the [/groups](#tag/Projects/operation/listProjects) endpoint to retrieve all projects to which the authenticated user has access.

            **NOTE**: Groups and projects are synonymous terms. Your group id is the same as your project id. For existing groups, your group/project id remains the same. The resource and corresponding endpoints use the term groups.

        tenant_name : str
            Human-readable label that identifies the Federated Database to return.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DataLakeTenant
            OK

        Examples
        --------
        import asyncio

        from atlas_sdk import AsyncAtlasClient

        client = AsyncAtlasClient(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.data_federation.get_data_federation(
                group_id="32b6e34b3d91647abb20e7b8",
                tenant_name="tenantName",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_data_federation(group_id, tenant_name, request_options=request_options)
        return _response.data

    async def delete_data_federation(
        self, group_id: str, tenant_name: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Any:
        """
        Removes one federated database instance from the specified project. To use this resource, the requesting Service Account or API Key must have the Project Owner or Project Charts Admin roles.

        Parameters
        ----------
        group_id : str
            Unique 24-hexadecimal digit string that identifies your project. Use the [/groups](#tag/Projects/operation/listProjects) endpoint to retrieve all projects to which the authenticated user has access.

            **NOTE**: Groups and projects are synonymous terms. Your group id is the same as your project id. For existing groups, your group/project id remains the same. The resource and corresponding endpoints use the term groups.

        tenant_name : str
            Human-readable label that identifies the federated database instance to remove.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Any
            This endpoint does not return a response body.

        Examples
        --------
        import asyncio

        from atlas_sdk import AsyncAtlasClient

        client = AsyncAtlasClient(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.data_federation.delete_data_federation(
                group_id="32b6e34b3d91647abb20e7b8",
                tenant_name="tenantName",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete_data_federation(
            group_id, tenant_name, request_options=request_options
        )
        return _response.data

    async def update_data_federation(
        self,
        group_id_: str,
        tenant_name: str,
        *,
        skip_role_validation: bool,
        cloud_provider_config: typing.Optional[DataLakeCloudProviderConfig] = OMIT,
        data_process_region: typing.Optional[DataLakeDataProcessRegion] = OMIT,
        group_id: typing.Optional[str] = OMIT,
        hostnames: typing.Optional[typing.Sequence[str]] = OMIT,
        name: typing.Optional[str] = OMIT,
        private_endpoint_hostnames: typing.Optional[typing.Sequence[PrivateEndpointHostname]] = OMIT,
        state: typing.Optional[str] = OMIT,
        storage: typing.Optional[DataLakeStorage] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> DataLakeTenant:
        """
        Updates the details of one federated database instance in the specified project. To use this resource, the requesting Service Account or API Key must have the Project Owner or higher role.

        Parameters
        ----------
        group_id_ : str
            Unique 24-hexadecimal digit string that identifies your project. Use the [/groups](#tag/Projects/operation/listProjects) endpoint to retrieve all projects to which the authenticated user has access.

            **NOTE**: Groups and projects are synonymous terms. Your group id is the same as your project id. For existing groups, your group/project id remains the same. The resource and corresponding endpoints use the term groups.

        tenant_name : str
            Human-readable label that identifies the federated database instance to update.

        skip_role_validation : bool
            Flag that indicates whether this request should check if the requesting IAM role can read from the S3 bucket. AWS checks if the role can list the objects in the bucket before writing to it. Some IAM roles only need write permissions. This flag allows you to skip that check.

        cloud_provider_config : typing.Optional[DataLakeCloudProviderConfig]

        data_process_region : typing.Optional[DataLakeDataProcessRegion]

        group_id : typing.Optional[str]
            Unique 24-hexadecimal character string that identifies the project.

        hostnames : typing.Optional[typing.Sequence[str]]
            List that contains the hostnames assigned to the Federated Database Instance.

        name : typing.Optional[str]
            Human-readable label that identifies the Federated Database Instance.

        private_endpoint_hostnames : typing.Optional[typing.Sequence[PrivateEndpointHostname]]
            List that contains the sets of private endpoints and hostnames.

        state : typing.Optional[str]
            Label that indicates the status of the Federated Database Instance.

        storage : typing.Optional[DataLakeStorage]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DataLakeTenant
            OK

        Examples
        --------
        import asyncio

        from atlas_sdk import AsyncAtlasClient

        client = AsyncAtlasClient(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.data_federation.update_data_federation(
                group_id_="32b6e34b3d91647abb20e7b8",
                tenant_name="tenantName",
                skip_role_validation=True,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update_data_federation(
            group_id_,
            tenant_name,
            skip_role_validation=skip_role_validation,
            cloud_provider_config=cloud_provider_config,
            data_process_region=data_process_region,
            group_id=group_id,
            hostnames=hostnames,
            name=name,
            private_endpoint_hostnames=private_endpoint_hostnames,
            state=state,
            storage=storage,
            request_options=request_options,
        )
        return _response.data

    async def list_data_federation_limits(
        self, group_id: str, tenant_name: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.List[DataFederationTenantQueryLimit]:
        """
        Returns query limits for a federated databases instance in the specified project. To use this resource, the requesting Service Account or API Key must have the Project Read Only role.

        Parameters
        ----------
        group_id : str
            Unique 24-hexadecimal digit string that identifies your project. Use the [/groups](#tag/Projects/operation/listProjects) endpoint to retrieve all projects to which the authenticated user has access.

            **NOTE**: Groups and projects are synonymous terms. Your group id is the same as your project id. For existing groups, your group/project id remains the same. The resource and corresponding endpoints use the term groups.

        tenant_name : str
            Human-readable label that identifies the federated database instance for which you want to retrieve query limits.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[DataFederationTenantQueryLimit]
            OK

        Examples
        --------
        import asyncio

        from atlas_sdk import AsyncAtlasClient

        client = AsyncAtlasClient(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.data_federation.list_data_federation_limits(
                group_id="32b6e34b3d91647abb20e7b8",
                tenant_name="tenantName",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list_data_federation_limits(
            group_id, tenant_name, request_options=request_options
        )
        return _response.data

    async def get_data_federation_limit(
        self,
        group_id: str,
        tenant_name: str,
        limit_name: str,
        *,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> DataFederationTenantQueryLimit:
        """
        Returns the details of one query limit for the specified federated database instance in the specified project. To use this resource, the requesting Service Account or API Key must have the Project Read Only role.

        Parameters
        ----------
        group_id : str
            Unique 24-hexadecimal digit string that identifies your project. Use the [/groups](#tag/Projects/operation/listProjects) endpoint to retrieve all projects to which the authenticated user has access.

            **NOTE**: Groups and projects are synonymous terms. Your group id is the same as your project id. For existing groups, your group/project id remains the same. The resource and corresponding endpoints use the term groups.

        tenant_name : str
            Human-readable label that identifies the federated database instance to which the query limit applies.

        limit_name : str
            Human-readable label that identifies this data federation instance limit.

            | Limit Name | Description | Default |
            | --- | --- | --- |
            | `bytesProcessed.query` | Limit on the number of bytes processed during a single data federation query | N/A |
            | `bytesProcessed.daily` | Limit on the number of bytes processed for the data federation instance for the current day | N/A |
            | `bytesProcessed.weekly` | Limit on the number of bytes processed for the data federation instance for the current week | N/A |
            | `bytesProcessed.monthly` | Limit on the number of bytes processed for the data federation instance for the current month | N/A |

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DataFederationTenantQueryLimit
            OK

        Examples
        --------
        import asyncio

        from atlas_sdk import AsyncAtlasClient

        client = AsyncAtlasClient(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.data_federation.get_data_federation_limit(
                group_id="32b6e34b3d91647abb20e7b8",
                tenant_name="tenantName",
                limit_name="limitName",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_data_federation_limit(
            group_id, tenant_name, limit_name, request_options=request_options
        )
        return _response.data

    async def delete_data_federation_limit(
        self,
        group_id: str,
        tenant_name: str,
        limit_name: str,
        *,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.Any:
        """
        Deletes one query limit for one federated database instance. To use this resource, the requesting Service Account or API Key must have the Project Owner role.

        Parameters
        ----------
        group_id : str
            Unique 24-hexadecimal digit string that identifies your project. Use the [/groups](#tag/Projects/operation/listProjects) endpoint to retrieve all projects to which the authenticated user has access.

            **NOTE**: Groups and projects are synonymous terms. Your group id is the same as your project id. For existing groups, your group/project id remains the same. The resource and corresponding endpoints use the term groups.

        tenant_name : str
            Human-readable label that identifies the federated database instance to which the query limit applies.

        limit_name : str
            Human-readable label that identifies this data federation instance limit.

            | Limit Name | Description | Default |
            | --- | --- | --- |
            | `bytesProcessed.query` | Limit on the number of bytes processed during a single data federation query | N/A |
            | `bytesProcessed.daily` | Limit on the number of bytes processed for the data federation instance for the current day | N/A |
            | `bytesProcessed.weekly` | Limit on the number of bytes processed for the data federation instance for the current week | N/A |
            | `bytesProcessed.monthly` | Limit on the number of bytes processed for the data federation instance for the current month | N/A |

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Any
            This endpoint does not return a response body.

        Examples
        --------
        import asyncio

        from atlas_sdk import AsyncAtlasClient

        client = AsyncAtlasClient(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.data_federation.delete_data_federation_limit(
                group_id="32b6e34b3d91647abb20e7b8",
                tenant_name="tenantName",
                limit_name="limitName",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete_data_federation_limit(
            group_id, tenant_name, limit_name, request_options=request_options
        )
        return _response.data

    async def set_data_federation_limit(
        self,
        group_id: str,
        tenant_name_: str,
        limit_name: str,
        *,
        value: int,
        current_usage: typing.Optional[int] = OMIT,
        default_limit: typing.Optional[int] = OMIT,
        last_modified_date: typing.Optional[dt.datetime] = OMIT,
        maximum_limit: typing.Optional[int] = OMIT,
        name: typing.Optional[str] = OMIT,
        overrun_policy: typing.Optional[str] = OMIT,
        tenant_name: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> DataFederationTenantQueryLimit:
        """
        Creates or updates one query limit for one federated database instance. To use this resource, the requesting Service Account or API Key must have the Project Owner role.

        Parameters
        ----------
        group_id : str
            Unique 24-hexadecimal digit string that identifies your project. Use the [/groups](#tag/Projects/operation/listProjects) endpoint to retrieve all projects to which the authenticated user has access.

            **NOTE**: Groups and projects are synonymous terms. Your group id is the same as your project id. For existing groups, your group/project id remains the same. The resource and corresponding endpoints use the term groups.

        tenant_name_ : str
            Human-readable label that identifies the federated database instance to which the query limit applies.

        limit_name : str
            Human-readable label that identifies this data federation instance limit.

            | Limit Name | Description | Default |
            | --- | --- | --- |
            | `bytesProcessed.query` | Limit on the number of bytes processed during a single data federation query | N/A |
            | `bytesProcessed.daily` | Limit on the number of bytes processed for the data federation instance for the current day | N/A |
            | `bytesProcessed.weekly` | Limit on the number of bytes processed for the data federation instance for the current week | N/A |
            | `bytesProcessed.monthly` | Limit on the number of bytes processed for the data federation instance for the current month | N/A |

        value : int
            Amount to set the limit to.

        current_usage : typing.Optional[int]
            Amount that indicates the current usage of the limit.

        default_limit : typing.Optional[int]
            Default value of the limit.

        last_modified_date : typing.Optional[dt.datetime]
            Only used for Data Federation limits. Timestamp that indicates when this usage limit was last modified. This field uses the ISO 8601 timestamp format in UTC.

        maximum_limit : typing.Optional[int]
            Maximum value of the limit.

        name : typing.Optional[str]
            Human-readable label that identifies the user-managed limit to modify.

        overrun_policy : typing.Optional[str]
            Only used for Data Federation limits. Action to take when the usage limit is exceeded. If limit span is set to QUERY, this is ignored because MongoDB Cloud stops the query when it exceeds the usage limit.

        tenant_name : typing.Optional[str]
            Human-readable label that identifies the Federated Database Instance. If specified, the usage limit is for the specified federated database instance only. If omitted, the usage limit is for all federated database instances in the project.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DataFederationTenantQueryLimit
            OK

        Examples
        --------
        import asyncio

        from atlas_sdk import AsyncAtlasClient

        client = AsyncAtlasClient(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.data_federation.set_data_federation_limit(
                group_id="32b6e34b3d91647abb20e7b8",
                tenant_name_="tenantName",
                limit_name="limitName",
                value=1000000,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.set_data_federation_limit(
            group_id,
            tenant_name_,
            limit_name,
            value=value,
            current_usage=current_usage,
            default_limit=default_limit,
            last_modified_date=last_modified_date,
            maximum_limit=maximum_limit,
            name=name,
            overrun_policy=overrun_policy,
            tenant_name=tenant_name,
            request_options=request_options,
        )
        return _response.data

    async def download_federation_query_logs(
        self,
        group_id: str,
        tenant_name: str,
        *,
        end_date: typing.Optional[int] = None,
        start_date: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.AsyncIterator[bytes]:
        """
        Downloads the query logs for the specified federated database instance. To use this resource, the requesting Service Account or API Key must have the Project Owner or Project Data Access Read Write roles. The API does not support direct calls with the json response schema. You must request a gzip response schema using an accept header of the format: `Accept: application/vnd.atlas.YYYY-MM-DD+gzip`.

        Parameters
        ----------
        group_id : str
            Unique 24-hexadecimal digit string that identifies your project. Use the [/groups](#tag/Projects/operation/listProjects) endpoint to retrieve all projects to which the authenticated user has access.

            **NOTE**: Groups and projects are synonymous terms. Your group id is the same as your project id. For existing groups, your group/project id remains the same. The resource and corresponding endpoints use the term groups.

        tenant_name : str
            Human-readable label that identifies the federated database instance for which you want to download query logs.

        end_date : typing.Optional[int]
            Timestamp that specifies the end point for the range of log messages to download.  MongoDB Cloud expresses this timestamp in the number of seconds that have elapsed since the UNIX epoch.

        start_date : typing.Optional[int]
            Timestamp that specifies the starting point for the range of log messages to download. MongoDB Cloud expresses this timestamp in the number of seconds that have elapsed since the UNIX epoch.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration. You can pass in configuration such as `chunk_size`, and more to customize the request and response.

        Returns
        -------
        typing.AsyncIterator[bytes]
            OK

        Examples
        --------
        import asyncio

        from atlas_sdk import AsyncAtlasClient

        client = AsyncAtlasClient(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.data_federation.download_federation_query_logs()


        asyncio.run(main())
        """
        async with self._raw_client.download_federation_query_logs(
            group_id, tenant_name, end_date=end_date, start_date=start_date, request_options=request_options
        ) as r:
            async for _chunk in r.data:
                yield _chunk

    async def list_private_endpoint_ids(
        self,
        group_id: str,
        *,
        include_count: typing.Optional[bool] = None,
        items_per_page: typing.Optional[int] = None,
        page_num: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PaginatedPrivateNetworkEndpointIdEntry:
        """
        Returns all private endpoints for Federated Database Instances and Online Archives in the specified project. To use this resource, the requesting Service Account or API Key must have the Project Read Only or Project Charts Admin roles.

        Parameters
        ----------
        group_id : str
            Unique 24-hexadecimal digit string that identifies your project. Use the [/groups](#tag/Projects/operation/listProjects) endpoint to retrieve all projects to which the authenticated user has access.

            **NOTE**: Groups and projects are synonymous terms. Your group id is the same as your project id. For existing groups, your group/project id remains the same. The resource and corresponding endpoints use the term groups.

        include_count : typing.Optional[bool]
            Flag that indicates whether the response returns the total number of items (`totalCount`) in the response.

        items_per_page : typing.Optional[int]
            Number of items that the response returns per page.

        page_num : typing.Optional[int]
            Number of the page that displays the current set of the total objects that the response returns.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PaginatedPrivateNetworkEndpointIdEntry
            OK

        Examples
        --------
        import asyncio

        from atlas_sdk import AsyncAtlasClient

        client = AsyncAtlasClient(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.data_federation.list_private_endpoint_ids(
                group_id="32b6e34b3d91647abb20e7b8",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list_private_endpoint_ids(
            group_id,
            include_count=include_count,
            items_per_page=items_per_page,
            page_num=page_num,
            request_options=request_options,
        )
        return _response.data

    async def create_private_endpoint_id(
        self,
        group_id: str,
        *,
        endpoint_id: str,
        azure_link_id: typing.Optional[str] = OMIT,
        comment: typing.Optional[str] = OMIT,
        customer_endpoint_dns_name: typing.Optional[str] = OMIT,
        customer_endpoint_ip_address: typing.Optional[str] = OMIT,
        error_message: typing.Optional[str] = OMIT,
        provider: typing.Optional[str] = OMIT,
        region: typing.Optional[str] = OMIT,
        status: typing.Optional[str] = OMIT,
        type: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PaginatedPrivateNetworkEndpointIdEntry:
        """
        Adds one private endpoint for Federated Database Instances and Online Archives to the specified projects. If the endpoint ID already exists and the associated comment is unchanged, Atlas Data Federation makes no change to the endpoint ID list. If the endpoint ID already exists and the associated comment is changed, Atlas Data Federation updates the comment value only in the endpoint ID list. If the endpoint ID doesn't exist, Atlas Data Federation appends the new endpoint to the list of endpoints in the endpoint ID list. Each region has an associated service name for the various endpoints. For the latest list of supported regions and their service names, see the external documentation. To use this resource, the requesting Service Account or API Key must have the Project Owner or Project Charts Admin roles.

        Parameters
        ----------
        group_id : str
            Unique 24-hexadecimal digit string that identifies your project. Use the [/groups](#tag/Projects/operation/listProjects) endpoint to retrieve all projects to which the authenticated user has access.

            **NOTE**: Groups and projects are synonymous terms. Your group id is the same as your project id. For existing groups, your group/project id remains the same. The resource and corresponding endpoints use the term groups.

        endpoint_id : str
            Unique 22-character alphanumeric string that identifies the private endpoint.

        azure_link_id : typing.Optional[str]
            Link ID that identifies the Azure private endpoint connection.

        comment : typing.Optional[str]
            Human-readable string to associate with this private endpoint.

        customer_endpoint_dns_name : typing.Optional[str]
            Human-readable label to identify customer's VPC endpoint DNS name. If defined, you must also specify a value for `region`.

        customer_endpoint_ip_address : typing.Optional[str]
            IP address used to connect to the Azure private endpoint.

        error_message : typing.Optional[str]
            Error message describing a failure approving the private endpoint request.

        provider : typing.Optional[str]
            Human-readable label that identifies the cloud service provider. Atlas Data Lake supports Amazon Web Services only.

        region : typing.Optional[str]
            Human-readable label to identify the region of customer's VPC endpoint. If defined, you must also specify a value for `customerEndpointDNSName`.

        status : typing.Optional[str]
            Status of the private endpoint connection request.

        type : typing.Optional[str]
            Human-readable label that identifies the resource type associated with this private endpoint.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PaginatedPrivateNetworkEndpointIdEntry
            OK

        Examples
        --------
        import asyncio

        from atlas_sdk import AsyncAtlasClient

        client = AsyncAtlasClient(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.data_federation.create_private_endpoint_id(
                group_id="32b6e34b3d91647abb20e7b8",
                endpoint_id="vpce-3bf78b0ddee411ba1",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_private_endpoint_id(
            group_id,
            endpoint_id=endpoint_id,
            azure_link_id=azure_link_id,
            comment=comment,
            customer_endpoint_dns_name=customer_endpoint_dns_name,
            customer_endpoint_ip_address=customer_endpoint_ip_address,
            error_message=error_message,
            provider=provider,
            region=region,
            status=status,
            type=type,
            request_options=request_options,
        )
        return _response.data

    async def get_private_endpoint_id(
        self, group_id: str, endpoint_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> PrivateNetworkEndpointIdEntry:
        """
        Returns the specified private endpoint for Federated Database Instances or Online Archives in the specified project. To use this resource, the requesting Service Account or API Key must have the Project Read Only or Project Charts Admin roles.

        Parameters
        ----------
        group_id : str
            Unique 24-hexadecimal digit string that identifies your project. Use the [/groups](#tag/Projects/operation/listProjects) endpoint to retrieve all projects to which the authenticated user has access.

            **NOTE**: Groups and projects are synonymous terms. Your group id is the same as your project id. For existing groups, your group/project id remains the same. The resource and corresponding endpoints use the term groups.

        endpoint_id : str
            Unique 22-character alphanumeric string that identifies the private endpoint to return. Atlas Data Federation supports AWS private endpoints using the AWS PrivateLink feature.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PrivateNetworkEndpointIdEntry
            OK

        Examples
        --------
        import asyncio

        from atlas_sdk import AsyncAtlasClient

        client = AsyncAtlasClient(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.data_federation.get_private_endpoint_id(
                group_id="32b6e34b3d91647abb20e7b8",
                endpoint_id="endpointId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_private_endpoint_id(
            group_id, endpoint_id, request_options=request_options
        )
        return _response.data

    async def delete_private_endpoint_id(
        self, group_id: str, endpoint_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Any:
        """
        Removes one private endpoint for Federated Database Instances and Online Archives in the specified project. To use this resource, the requesting Service Account or API Key must have the Project Owner role.

        Parameters
        ----------
        group_id : str
            Unique 24-hexadecimal digit string that identifies your project. Use the [/groups](#tag/Projects/operation/listProjects) endpoint to retrieve all projects to which the authenticated user has access.

            **NOTE**: Groups and projects are synonymous terms. Your group id is the same as your project id. For existing groups, your group/project id remains the same. The resource and corresponding endpoints use the term groups.

        endpoint_id : str
            Unique 22-character alphanumeric string that identifies the private endpoint to remove. Atlas Data Federation supports AWS private endpoints using the AWS PrivateLink feature.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Any
            This endpoint does not return a response body.

        Examples
        --------
        import asyncio

        from atlas_sdk import AsyncAtlasClient

        client = AsyncAtlasClient(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.data_federation.delete_private_endpoint_id(
                group_id="32b6e34b3d91647abb20e7b8",
                endpoint_id="endpointId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete_private_endpoint_id(
            group_id, endpoint_id, request_options=request_options
        )
        return _response.data
