# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class AccessListItem(UniversalBaseModel):
    cidr_block: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="cidrBlock"),
        pydantic.Field(
            alias="cidrBlock",
            description="Range of IP addresses in Classless Inter-Domain Routing (CIDR) notation that found in this project's access list.",
        ),
    ] = None
    ip_address: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="ipAddress"),
        pydantic.Field(alias="ipAddress", description="IP address included in the API access list."),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
