# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .disk_backup_api_policy_item import DiskBackupApiPolicyItem


class AdvancedDiskBackupSnapshotSchedulePolicy(UniversalBaseModel):
    """
    List that contains a document for each backup policy item in the desired backup policy.
    """

    id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Unique 24-hexadecimal digit string that identifies this backup policy.
    """

    policy_items: typing_extensions.Annotated[
        typing.List[DiskBackupApiPolicyItem],
        FieldMetadata(alias="policyItems"),
        pydantic.Field(alias="policyItems", description="List that contains the specifications for one policy."),
    ]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
