# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class ApiAtlasFtsAnalyzersTokenizer(UniversalBaseModel):
    """
    Tokenizer that you want to use to create tokens. Tokens determine how Atlas Search splits up text into discrete chunks for indexing.
    """

    max_gram: typing_extensions.Annotated[
        typing.Optional[int],
        FieldMetadata(alias="maxGram"),
        pydantic.Field(
            alias="maxGram", description="Characters to include in the longest token that Atlas Search creates."
        ),
    ] = None
    min_gram: typing_extensions.Annotated[
        typing.Optional[int],
        FieldMetadata(alias="minGram"),
        pydantic.Field(
            alias="minGram", description="Characters to include in the shortest token that Atlas Search creates."
        ),
    ] = None
    type: typing.Optional[str] = pydantic.Field(default=None)
    """
    Human-readable label that identifies this tokenizer type.
    """

    group: typing.Optional[int] = pydantic.Field(default=None)
    """
    Index of the character group within the matching expression to extract into tokens. Use `0` to extract all character groups.
    """

    pattern: typing.Optional[str] = pydantic.Field(default=None)
    """
    Regular expression to match against.
    """

    max_token_length: typing_extensions.Annotated[
        typing.Optional[int],
        FieldMetadata(alias="maxTokenLength"),
        pydantic.Field(
            alias="maxTokenLength",
            description="Maximum number of characters in a single token. Tokens greater than this length are split at this length into multiple tokens.",
        ),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
