# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class ApiAtlasFtsMappings(UniversalBaseModel):
    """
    Index specifications for the collection's fields.
    """

    dynamic: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Flag that indicates whether the index uses dynamic or static mappings. Required if `mappings.fields` is omitted.
    """

    fields: typing.Optional[typing.Dict[str, typing.Any]] = pydantic.Field(default=None)
    """
    One or more field specifications for the Atlas Search index. Required if `mappings.dynamic` is omitted or set to `false`.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
