# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .api_atlas_policy_metadata import ApiAtlasPolicyMetadata


class ApiAtlasResourcePolicyMetadata(UniversalBaseModel):
    policies_causing_non_compliance: typing_extensions.Annotated[
        typing.Optional[typing.List[ApiAtlasPolicyMetadata]],
        FieldMetadata(alias="policiesCausingNonCompliance"),
        pydantic.Field(
            alias="policiesCausingNonCompliance",
            description="List of policies that are in conflict with the current state of the resource.",
        ),
    ] = None
    resource_policy_id: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="resourcePolicyId"),
        pydantic.Field(
            alias="resourcePolicyId",
            description="Unique 24-hexadecimal character string that identifies the atlas resource policy.",
        ),
    ] = None
    resource_policy_name: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="resourcePolicyName"),
        pydantic.Field(
            alias="resourcePolicyName", description="Human-readable label that describes the atlas resource policy."
        ),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
