# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .api_bson_timestamp import ApiBsonTimestamp


class ApiCheckpointPart(UniversalBaseModel):
    """
    Metadata contained in one document that describes the complete snapshot taken for this node.
    """

    replica_set_name: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="replicaSetName"),
        pydantic.Field(
            alias="replicaSetName",
            description="Human-readable label that identifies the replica set to which this checkpoint applies.",
        ),
    ] = None
    shard_name: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="shardName"),
        pydantic.Field(
            alias="shardName",
            description="Human-readable label that identifies the shard to which this checkpoint applies.",
        ),
    ] = None
    token_discovered: typing_extensions.Annotated[
        typing.Optional[bool],
        FieldMetadata(alias="tokenDiscovered"),
        pydantic.Field(alias="tokenDiscovered", description="Flag that indicates whether the token exists."),
    ] = None
    token_timestamp: typing_extensions.Annotated[
        typing.Optional[ApiBsonTimestamp], FieldMetadata(alias="tokenTimestamp"), pydantic.Field(alias="tokenTimestamp")
    ] = None
    type_name: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="typeName"),
        pydantic.Field(
            alias="typeName",
            description="Human-readable label that identifies the type of host that the part represents.",
        ),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
