# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .api_atlas_invalid_policy_error_detail import ApiAtlasInvalidPolicyErrorDetail


class ApiAtlasInvalidPolicy(UniversalBaseModel):
    body: typing.Optional[str] = pydantic.Field(default=None)
    """
    A string that defines the permissions for the policy. The syntax used is the Cedar Policy language.
    """

    errors: typing.Optional[typing.List[ApiAtlasInvalidPolicyErrorDetail]] = pydantic.Field(default=None)
    """
    List of validation errors.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
