# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .api_checkpoint_part import ApiCheckpointPart
from .link import Link


class ApiAtlasCheckpoint(UniversalBaseModel):
    cluster_id: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="clusterId"),
        pydantic.Field(
            alias="clusterId",
            description="Unique 24-hexadecimal digit string that identifies the cluster that contains the checkpoint.",
        ),
    ] = None
    completed: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    Date and time when the checkpoint completed and the balancer restarted. This parameter expresses its value in the ISO 8601 timestamp format in UTC.
    """

    group_id: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="groupId"),
        pydantic.Field(
            alias="groupId",
            description="Unique 24-hexadecimal digit string that identifies the project that owns the checkpoints.",
        ),
    ] = None
    id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Unique 24-hexadecimal digit string that identifies checkpoint.
    """

    links: typing.Optional[typing.List[Link]] = pydantic.Field(default=None)
    """
    List of one or more Uniform Resource Locators (URLs) that point to API sub-resources, related API resources, or both. RFC 5988 outlines these relationships.
    """

    parts: typing.Optional[typing.List[ApiCheckpointPart]] = pydantic.Field(default=None)
    """
    Metadata that describes the complete snapshot.
    
    - For a replica set, this array contains a single document.
    - For a sharded cluster, this array contains one document for each shard plus one document for the config host.
    """

    restorable: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Flag that indicates whether MongoDB Cloud can use the checkpoint for a restore.
    """

    started: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    Date and time when the balancer stopped and began the checkpoint. This parameter expresses its value in the ISO 8601 timestamp format in UTC.
    """

    timestamp: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    Date and time to which the checkpoint restores. This parameter expresses its value in the ISO 8601 timestamp format in UTC.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
