# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class AutoExportPolicy(UniversalBaseModel):
    """
    Policy for automatically exporting Cloud Backup Snapshots.
    """

    export_bucket_id: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="exportBucketId"),
        pydantic.Field(
            alias="exportBucketId",
            description="Unique 24-hexadecimal character string that identifies the Export Bucket.",
        ),
    ] = None
    frequency_type: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="frequencyType"),
        pydantic.Field(
            alias="frequencyType",
            description="Human-readable label that indicates the rate at which the export policy item occurs.",
        ),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
