# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel, update_forward_refs
from ..core.serialization import FieldMetadata
from .billing_payment import BillingPayment
from .billing_refund import BillingRefund
from .invoice_line_item import InvoiceLineItem
from .link import Link


class BillingInvoice(UniversalBaseModel):
    amount_billed_cents: typing_extensions.Annotated[
        typing.Optional[int],
        FieldMetadata(alias="amountBilledCents"),
        pydantic.Field(
            alias="amountBilledCents",
            description="Sum of services that the specified organization consumed in the period covered in this invoice. This parameter expresses its value in cents (100ths of one US Dollar).",
        ),
    ] = None
    amount_paid_cents: typing_extensions.Annotated[
        typing.Optional[int],
        FieldMetadata(alias="amountPaidCents"),
        pydantic.Field(
            alias="amountPaidCents",
            description="Sum that the specified organization paid toward this invoice. This parameter expresses its value in cents (100ths of one US Dollar).",
        ),
    ] = None
    created: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    Date and time when MongoDB Cloud created this invoice. This parameter expresses its value in the ISO 8601 timestamp format in UTC.
    """

    credits_cents: typing_extensions.Annotated[
        typing.Optional[int],
        FieldMetadata(alias="creditsCents"),
        pydantic.Field(
            alias="creditsCents",
            description="Sum that MongoDB credited the specified organization toward this invoice. This parameter expresses its value in cents (100ths of one US Dollar).",
        ),
    ] = None
    end_date: typing_extensions.Annotated[
        typing.Optional[dt.datetime],
        FieldMetadata(alias="endDate"),
        pydantic.Field(
            alias="endDate",
            description="Date and time when MongoDB Cloud finished the billing period that this invoice covers. This parameter expresses its value in the ISO 8601 timestamp format in UTC.",
        ),
    ] = None
    id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Unique 24-hexadecimal digit string that identifies the invoice submitted to the specified organization. Charges typically post the next day.
    """

    line_items: typing_extensions.Annotated[
        typing.Optional[typing.List[InvoiceLineItem]],
        FieldMetadata(alias="lineItems"),
        pydantic.Field(
            alias="lineItems", description="List that contains individual services included in this invoice."
        ),
    ] = None
    linked_invoices: typing_extensions.Annotated[
        typing.Optional[typing.List["BillingInvoice"]],
        FieldMetadata(alias="linkedInvoices"),
        pydantic.Field(
            alias="linkedInvoices",
            description="List that contains the invoices for organizations linked to the paying organization.",
        ),
    ] = None
    links: typing.Optional[typing.List[Link]] = pydantic.Field(default=None)
    """
    List of one or more Uniform Resource Locators (URLs) that point to API sub-resources, related API resources, or both. RFC 5988 outlines these relationships.
    """

    org_id: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="orgId"),
        pydantic.Field(
            alias="orgId",
            description="Unique 24-hexadecimal digit string that identifies the organization charged for services consumed from MongoDB Cloud.",
        ),
    ] = None
    payments: typing.Optional[typing.List[BillingPayment]] = pydantic.Field(default=None)
    """
    List that contains funds transferred to MongoDB to cover the specified service noted in this invoice.
    """

    refunds: typing.Optional[typing.List[BillingRefund]] = pydantic.Field(default=None)
    """
    List that contains payments that MongoDB returned to the organization for this invoice.
    """

    sales_tax_cents: typing_extensions.Annotated[
        typing.Optional[int],
        FieldMetadata(alias="salesTaxCents"),
        pydantic.Field(
            alias="salesTaxCents",
            description="Sum of sales tax applied to this invoice. This parameter expresses its value in cents (100ths of one US Dollar).",
        ),
    ] = None
    start_date: typing_extensions.Annotated[
        typing.Optional[dt.datetime],
        FieldMetadata(alias="startDate"),
        pydantic.Field(
            alias="startDate",
            description="Date and time when MongoDB Cloud began the billing period that this invoice covers. This parameter expresses its value in the ISO 8601 timestamp format in UTC.",
        ),
    ] = None
    starting_balance_cents: typing_extensions.Annotated[
        typing.Optional[int],
        FieldMetadata(alias="startingBalanceCents"),
        pydantic.Field(
            alias="startingBalanceCents",
            description="Sum that the specified organization owed to MongoDB when MongoDB issued this invoice. This parameter expresses its value in US Dollars.",
        ),
    ] = None
    status_name: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="statusName"),
        pydantic.Field(
            alias="statusName",
            description="Phase of payment processing in which this invoice exists when you made this request. Accepted phases include:\n\n- `CLOSED`: MongoDB finalized all charges in the billing cycle but has yet to charge the customer.\n- `FAILED`: MongoDB attempted to charge the provided credit card but charge for that amount failed.\n- `FORGIVEN`: Customer initiated payment which MongoDB later forgave.\n- `FREE`: All charges totalled zero so the customer won't be charged.\n- `INVOICED`: MongoDB handled these charges using elastic invoicing.\n- `PAID`: MongoDB succeeded in charging the provided credit card.\n- `PENDING`: Invoice includes charges for the current billing cycle.\n- `PREPAID`: Customer has a pre-paid plan so they won't be charged.",
        ),
    ] = None
    subtotal_cents: typing_extensions.Annotated[
        typing.Optional[int],
        FieldMetadata(alias="subtotalCents"),
        pydantic.Field(
            alias="subtotalCents",
            description="Sum of all positive invoice line items contained in this invoice. This parameter expresses its value in cents (100ths of one US Dollar).",
        ),
    ] = None
    updated: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    Date and time when MongoDB Cloud last updated the value of this payment. This parameter expresses its value in the ISO 8601 timestamp format in UTC.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


update_forward_refs(BillingInvoice)
