# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .cluster_compute_auto_scaling import ClusterComputeAutoScaling


class ClusterAutoScalingSettings(UniversalBaseModel):
    """
    Range of instance sizes to which your cluster can scale.
    """

    compute: typing.Optional[ClusterComputeAutoScaling] = None
    disk_gb_enabled: typing_extensions.Annotated[
        typing.Optional[bool],
        FieldMetadata(alias="diskGBEnabled"),
        pydantic.Field(
            alias="diskGBEnabled",
            description="Flag that indicates whether someone enabled disk auto-scaling for this cluster.",
        ),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
