# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .cluster_free_auto_scaling import ClusterFreeAutoScaling


class ClusterProviderSettings(UniversalBaseModel):
    """
    Group of cloud provider settings that configure the provisioned MongoDB hosts.
    """

    provider_name: typing_extensions.Annotated[
        str, FieldMetadata(alias="providerName"), pydantic.Field(alias="providerName")
    ]
    auto_scaling: typing_extensions.Annotated[
        typing.Optional[ClusterFreeAutoScaling], FieldMetadata(alias="autoScaling"), pydantic.Field(alias="autoScaling")
    ] = None
    disk_iops: typing_extensions.Annotated[
        typing.Optional[int],
        FieldMetadata(alias="diskIOPS"),
        pydantic.Field(
            alias="diskIOPS",
            description="Maximum Disk Input/Output Operations per Second (IOPS) that the database host can perform.",
        ),
    ] = None
    encrypt_ebs_volume: typing_extensions.Annotated[
        typing.Optional[bool],
        FieldMetadata(alias="encryptEBSVolume"),
        pydantic.Field(
            alias="encryptEBSVolume",
            description="Flag that indicates whether the Amazon Elastic Block Store (EBS) encryption feature encrypts the host's root volume for both data at rest within the volume and for data moving between the volume and the cluster. Clusters always have this setting enabled.",
        ),
    ] = None
    instance_size_name: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="instanceSizeName"),
        pydantic.Field(
            alias="instanceSizeName",
            description="Cluster tier, with a default storage and memory capacity, that applies to all the data-bearing hosts in your cluster. You must set `providerSettings.providerName` to `FLEX` and specify the cloud service provider in `providerSettings.backingProviderName`.",
        ),
    ] = None
    region_name: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="regionName"),
        pydantic.Field(
            alias="regionName",
            description="Human-readable label that identifies the geographic location of your MongoDB cluster. The region you choose can affect network latency for clients accessing your databases. For a complete list of region names, see [AWS](https://docs.atlas.mongodb.com/reference/amazon-aws/#std-label-amazon-aws), [GCP](https://docs.atlas.mongodb.com/reference/google-gcp/), and [Azure](https://docs.atlas.mongodb.com/reference/microsoft-azure/).",
        ),
    ] = None
    volume_type: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="volumeType"),
        pydantic.Field(
            alias="volumeType",
            description="Disk Input/Output Operations per Second (IOPS) setting for Amazon Web Services (AWS) storage that you configure only for AWS. Specify whether Disk Input/Output Operations per Second (IOPS) must not exceed the default Input/Output Operations per Second (IOPS) rate for the selected volume size (`STANDARD`), or must fall within the allowable Input/Output Operations per Second (IOPS) range for the selected volume size (`PROVISIONED`). You must set this value to (`PROVISIONED`) for NVMe clusters.",
        ),
    ] = None
    disk_type_name: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="diskTypeName"),
        pydantic.Field(
            alias="diskTypeName",
            description="Disk type that corresponds to the host's root volume for Azure instances. If omitted, the default disk type for the selected `providerSettings.instanceSizeName` applies.",
        ),
    ] = None
    backing_provider_name: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="backingProviderName"),
        pydantic.Field(
            alias="backingProviderName",
            description="Cloud service provider on which MongoDB Cloud provisioned the multi-tenant host. The resource returns this parameter when `providerSettings.providerName` is `FLEX` and `providerSetting.instanceSizeName` is `FLEX`.",
        ),
    ] = None
    effective_instance_size_name: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="effectiveInstanceSizeName"),
        pydantic.Field(
            alias="effectiveInstanceSizeName",
            description="The true tenant instance size. This is present to support backwards compatibility for deprecated provider types and/or instance sizes.",
        ),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
