# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .cluster_description_connection_strings_private_endpoint_endpoint import (
    ClusterDescriptionConnectionStringsPrivateEndpointEndpoint,
)


class ClusterDescriptionConnectionStringsPrivateEndpoint(UniversalBaseModel):
    """
    Private endpoint-aware connection string that you can use to connect to this cluster through a private endpoint.
    """

    connection_string: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="connectionString"),
        pydantic.Field(
            alias="connectionString",
            description="Private endpoint-aware connection string that uses the `mongodb://` protocol to connect to MongoDB Cloud through a private endpoint.",
        ),
    ] = None
    endpoints: typing.Optional[typing.List[ClusterDescriptionConnectionStringsPrivateEndpointEndpoint]] = (
        pydantic.Field(default=None)
    )
    """
    List that contains the private endpoints through which you connect to MongoDB Cloud when you use `connectionStrings.privateEndpoint[n].connectionString` or `connectionStrings.privateEndpoint[n].srvConnectionString`.
    """

    srv_connection_string: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="srvConnectionString"),
        pydantic.Field(
            alias="srvConnectionString",
            description="Private endpoint-aware connection string that uses the `mongodb+srv://` protocol to connect to MongoDB Cloud through a private endpoint. The `mongodb+srv` protocol tells the driver to look up the seed list of hosts in the Domain Name System (DNS). This list synchronizes with the nodes in a cluster. If the connection string uses this Uniform Resource Identifier (URI) format, you don't need to append the seed list or change the Uniform Resource Identifier (URI) if the nodes change. Use this Uniform Resource Identifier (URI) format if your application supports it. If it doesn't, use `connectionStrings.privateEndpoint[n].connectionString`.",
        ),
    ] = None
    srv_shard_optimized_connection_string: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="srvShardOptimizedConnectionString"),
        pydantic.Field(
            alias="srvShardOptimizedConnectionString",
            description="Private endpoint-aware connection string optimized for sharded clusters that uses the `mongodb+srv://` protocol to connect to MongoDB Cloud through a private endpoint. If the connection string uses this Uniform Resource Identifier (URI) format, you don't need to change the Uniform Resource Identifier (URI) if the nodes change. Use this Uniform Resource Identifier (URI) format if your application and Atlas cluster supports it. If it doesn't, use and consult the documentation for `connectionStrings.privateEndpoint[n].srvConnectionString`.",
        ),
    ] = None
    type: typing.Optional[str] = pydantic.Field(default=None)
    """
    MongoDB process type to which your application connects. Use `MONGOD` for replica sets and `MONGOS` for sharded clusters.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
