# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class DataLakeDatabaseDataSourceSettings(UniversalBaseModel):
    """
    Data store that maps to a collection for this data lake.
    """

    allow_insecure: typing_extensions.Annotated[
        typing.Optional[bool],
        FieldMetadata(alias="allowInsecure"),
        pydantic.Field(
            alias="allowInsecure",
            description="Flag that validates the scheme in the specified URLs. If `true`, allows insecure `HTTP` scheme, doesn't verify the server's certificate chain and hostname, and accepts any certificate with any hostname presented by the server. If `false`, allows secure `HTTPS` scheme only.",
        ),
    ] = None
    collection: typing.Optional[str] = pydantic.Field(default=None)
    """
    Human-readable label that identifies the collection in the database. For creating a wildcard (`*`) collection, you must omit this parameter.
    """

    collection_regex: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="collectionRegex"),
        pydantic.Field(
            alias="collectionRegex",
            description="Regex pattern to use for creating the wildcard (*) collection. To learn more about the regex syntax, see [Go programming language](https://pkg.go.dev/regexp).",
        ),
    ] = None
    database: typing.Optional[str] = pydantic.Field(default=None)
    """
    Human-readable label that identifies the database, which contains the collection in the cluster. You must omit this parameter to generate wildcard (`*`) collections for dynamically generated databases.
    """

    database_regex: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="databaseRegex"),
        pydantic.Field(
            alias="databaseRegex",
            description="Regex pattern to use for creating the wildcard (*) database. To learn more about the regex syntax, see [Go programming language](https://pkg.go.dev/regexp).",
        ),
    ] = None
    dataset_name: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="datasetName"),
        pydantic.Field(
            alias="datasetName",
            description="Human-readable label that identifies the dataset that Atlas generates for an ingestion pipeline run or Online Archive.",
        ),
    ] = None
    dataset_prefix: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="datasetPrefix"),
        pydantic.Field(
            alias="datasetPrefix",
            description="Human-readable label that matches against the dataset names for ingestion pipeline runs or Online Archives.",
        ),
    ] = None
    default_format: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="defaultFormat"),
        pydantic.Field(
            alias="defaultFormat",
            description="File format that MongoDB Cloud uses if it encounters a file without a file extension while searching **storeName**.",
        ),
    ] = None
    path: typing.Optional[str] = pydantic.Field(default=None)
    """
    File path that controls how MongoDB Cloud searches for and parses files in the **storeName** before mapping them to a collection.Specify ``/`` to capture all files and folders from the ``prefix`` path.
    """

    provenance_field_name: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="provenanceFieldName"),
        pydantic.Field(
            alias="provenanceFieldName",
            description="Name for the field that includes the provenance of the documents in the results. MongoDB Cloud returns different fields in the results for each supported provider.",
        ),
    ] = None
    store_name: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="storeName"),
        pydantic.Field(
            alias="storeName",
            description="Human-readable label that identifies the data store that MongoDB Cloud maps to the collection.",
        ),
    ] = None
    trim_level: typing_extensions.Annotated[
        typing.Optional[int],
        FieldMetadata(alias="trimLevel"),
        pydantic.Field(
            alias="trimLevel",
            description="Unsigned integer that specifies how many fields of the dataset name to trim from the left of the dataset name before mapping the remaining fields to a wildcard collection name.",
        ),
    ] = None
    urls: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    URLs of the publicly accessible data files. You can't specify URLs that require authentication. Atlas Data Lake creates a partition for each URL. If empty or omitted, Data Lake uses the URLs from the store specified in the **dataSources.storeName** parameter.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
