# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class DataLakeAtlasStoreReadConcern(UniversalBaseModel):
    """
    MongoDB Cloud cluster read concern, which determines the consistency and isolation properties of the data read from an Atlas cluster.
    """

    level: typing.Optional[str] = pydantic.Field(default=None)
    """
    Read Concern level that specifies the consistency and availability of the data read.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
