# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class DataExpirationRule(UniversalBaseModel):
    """
    Rule for specifying when data should be deleted from the archive.
    """

    expire_after_days: typing_extensions.Annotated[
        typing.Optional[int],
        FieldMetadata(alias="expireAfterDays"),
        pydantic.Field(
            alias="expireAfterDays",
            description="Number of days used in the date criteria for nominating documents for deletion.",
        ),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
