# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .dataset_retention_policy import DatasetRetentionPolicy
from .field_transformation import FieldTransformation
from .ingestion_sink import IngestionSink
from .ingestion_source import IngestionSource


class DataLakeIngestionPipeline(UniversalBaseModel):
    """
    Details of a Data Lake Pipeline.
    """

    id: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="_id"),
        pydantic.Field(
            alias="_id", description="Unique 24-hexadecimal digit string that identifies the Data Lake Pipeline."
        ),
    ] = None
    created_date: typing_extensions.Annotated[
        typing.Optional[dt.datetime],
        FieldMetadata(alias="createdDate"),
        pydantic.Field(
            alias="createdDate",
            description="Timestamp that indicates when the Data Lake Pipeline was created. This parameter expresses its value in the ISO 8601 timestamp format in UTC.",
        ),
    ] = None
    dataset_retention_policy: typing_extensions.Annotated[
        typing.Optional[DatasetRetentionPolicy],
        FieldMetadata(alias="datasetRetentionPolicy"),
        pydantic.Field(alias="datasetRetentionPolicy"),
    ] = None
    group_id: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="groupId"),
        pydantic.Field(alias="groupId", description="Unique 24-hexadecimal digit string that identifies the group."),
    ] = None
    last_updated_date: typing_extensions.Annotated[
        typing.Optional[dt.datetime],
        FieldMetadata(alias="lastUpdatedDate"),
        pydantic.Field(
            alias="lastUpdatedDate",
            description="Timestamp that indicates the last time that the Data Lake Pipeline was updated. This parameter expresses its value in the ISO 8601 timestamp format in UTC.",
        ),
    ] = None
    name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Name of this Data Lake Pipeline.
    """

    sink: typing.Optional[IngestionSink] = None
    source: typing.Optional[IngestionSource] = None
    state: typing.Optional[str] = pydantic.Field(default=None)
    """
    State of this Data Lake Pipeline.
    """

    transformations: typing.Optional[typing.List[FieldTransformation]] = pydantic.Field(default=None)
    """
    Fields to be excluded for this Data Lake Pipeline.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
