# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class Destination(UniversalBaseModel):
    """
    Document that describes the destination of the migration.
    """

    cluster_name: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="clusterName"),
        pydantic.Field(alias="clusterName", description="Label that identifies the destination cluster."),
    ]
    group_id: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="groupId"),
        pydantic.Field(
            alias="groupId", description="Unique 24-hexadecimal digit string that identifies the destination project."
        ),
    ]
    hostname_schema_type: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="hostnameSchemaType"),
        pydantic.Field(
            alias="hostnameSchemaType",
            description="The network type to use between the migration host and the destination cluster.",
        ),
    ]
    private_link_id: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="privateLinkId"),
        pydantic.Field(
            alias="privateLinkId",
            description="Represents the endpoint to use when the host schema type is `PRIVATE_LINK`.",
        ),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
