# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .link import Link


class DiskBackupSnapshotExportBucketResponse(UniversalBaseModel):
    """
    Disk backup snapshot Export Bucket.
    """

    id: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="_id"),
        pydantic.Field(
            alias="_id", description="Unique 24-hexadecimal character string that identifies the Export Bucket."
        ),
    ]
    bucket_name: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="bucketName"),
        pydantic.Field(
            alias="bucketName",
            description="The name of the AWS S3 Bucket, Azure Storage Container, or Google Cloud Storage Bucket that Snapshots are exported to.",
        ),
    ]
    cloud_provider: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="cloudProvider"),
        pydantic.Field(alias="cloudProvider", description="Human-readable label that identifies the cloud provider."),
    ]
    links: typing.Optional[typing.List[Link]] = pydantic.Field(default=None)
    """
    List of one or more Uniform Resource Locators (URLs) that point to API sub-resources, related API resources, or both. RFC 5988 outlines these relationships.
    """

    iam_role_id: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="iamRoleId"),
        pydantic.Field(
            alias="iamRoleId",
            description="Unique 24-hexadecimal character string that identifies the Unified AWS Access role ID that MongoDB Cloud uses to access the AWS S3 bucket.",
        ),
    ] = None
    region: typing.Optional[str] = pydantic.Field(default=None)
    """
    AWS region for the export bucket. This is set by Atlas and is never user-supplied.
    """

    require_private_networking: typing_extensions.Annotated[
        typing.Optional[bool],
        FieldMetadata(alias="requirePrivateNetworking"),
        pydantic.Field(
            alias="requirePrivateNetworking", description="Indicates whether to use private link. User supplied."
        ),
    ] = None
    role_id: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="roleId"),
        pydantic.Field(
            alias="roleId",
            description="Unique 24-hexadecimal digit string that identifies the GCP Cloud Provider Access Role that MongoDB Cloud uses to access the Google Cloud Storage Bucket.",
        ),
    ] = None
    service_url: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="serviceUrl"),
        pydantic.Field(
            alias="serviceUrl",
            description="URL of the Azure Storage Account to export to. Only standard endpoints (with `blob.core.windows.net`) are supported.",
        ),
    ] = None
    tenant_id: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="tenantId"),
        pydantic.Field(
            alias="tenantId",
            description="UUID that identifies the Azure Active Directory Tenant ID used during exports.",
        ),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
