# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class EarPrivateEndpoint(UniversalBaseModel):
    """
    Encryption At Rest Private Endpoint.
    """

    cloud_provider: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="cloudProvider"),
        pydantic.Field(
            alias="cloudProvider",
            description="Human-readable label that identifies the cloud provider for the Encryption At Rest private endpoint.",
        ),
    ] = None
    error_message: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="errorMessage"),
        pydantic.Field(
            alias="errorMessage",
            description="Error message for failures associated with the Encryption At Rest private endpoint.",
        ),
    ] = None
    id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Unique 24-hexadecimal digit string that identifies the Private Endpoint Service.
    """

    region_name: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="regionName"),
        pydantic.Field(
            alias="regionName",
            description="Cloud provider region in which the Encryption At Rest private endpoint is located.",
        ),
    ] = None
    status: typing.Optional[str] = pydantic.Field(default=None)
    """
    State of the Encryption At Rest private endpoint.
    """

    private_endpoint_connection_name: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="privateEndpointConnectionName"),
        pydantic.Field(alias="privateEndpointConnectionName", description="Resource Id of the Aws Private Endpoint."),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
