# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class FieldTransformation(UniversalBaseModel):
    """
    Field Transformations during ingestion of a Data Lake Pipeline.
    """

    field: typing.Optional[str] = pydantic.Field(default=None)
    """
    Key in the document.
    """

    type: typing.Optional[str] = pydantic.Field(default=None)
    """
    Type of transformation applied during the export of the namespace in a Data Lake Pipeline.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
