# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .link import Link


class FlexBackupSnapshot20241113(UniversalBaseModel):
    """
    Details for one snapshot of a flex cluster.
    """

    expiration: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    Date and time when the download link no longer works. This parameter expresses its value in the ISO 8601 timestamp format in UTC.
    """

    finish_time: typing_extensions.Annotated[
        typing.Optional[dt.datetime],
        FieldMetadata(alias="finishTime"),
        pydantic.Field(
            alias="finishTime",
            description="Date and time when MongoDB Cloud completed writing this snapshot. This parameter expresses its value in the ISO 8601 timestamp format in UTC.",
        ),
    ] = None
    id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Unique 24-hexadecimal digit string that identifies the snapshot.
    """

    links: typing.Optional[typing.List[Link]] = pydantic.Field(default=None)
    """
    List of one or more Uniform Resource Locators (URLs) that point to API sub-resources, related API resources, or both. RFC 5988 outlines these relationships.
    """

    mongo_db_version: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="mongoDBVersion"),
        pydantic.Field(alias="mongoDBVersion", description="MongoDB host version that the snapshot runs."),
    ] = None
    scheduled_time: typing_extensions.Annotated[
        typing.Optional[dt.datetime],
        FieldMetadata(alias="scheduledTime"),
        pydantic.Field(
            alias="scheduledTime",
            description="Date and time when MongoDB Cloud will take the snapshot. This parameter expresses its value in the ISO 8601 timestamp format in UTC.",
        ),
    ] = None
    start_time: typing_extensions.Annotated[
        typing.Optional[dt.datetime],
        FieldMetadata(alias="startTime"),
        pydantic.Field(
            alias="startTime",
            description="Date and time when MongoDB Cloud began taking the snapshot. This parameter expresses its value in the ISO 8601 timestamp format in UTC.",
        ),
    ] = None
    status: typing.Optional[str] = pydantic.Field(default=None)
    """
    Phase of the workflow for this snapshot at the time this resource made this request.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
