# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .cluster_ip_addresses import ClusterIpAddresses


class GroupService(UniversalBaseModel):
    """
    List of IP addresses in a project categorized by services.
    """

    clusters: typing.Optional[typing.List[ClusterIpAddresses]] = pydantic.Field(default=None)
    """
    IP addresses of clusters.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
