# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .link import Link
from .user_to_dn_mapping import UserToDnMapping


class LdapSecuritySettings(UniversalBaseModel):
    """
    Lightweight Directory Access Protocol (LDAP) over Transport Layer Security (TLS) configuration details that apply to the specified project.
    """

    authentication_enabled: typing_extensions.Annotated[
        typing.Optional[bool],
        FieldMetadata(alias="authenticationEnabled"),
        pydantic.Field(
            alias="authenticationEnabled",
            description="Flag that indicates whether users can authenticate using an Lightweight Directory Access Protocol (LDAP) host.",
        ),
    ] = None
    authorization_enabled: typing_extensions.Annotated[
        typing.Optional[bool],
        FieldMetadata(alias="authorizationEnabled"),
        pydantic.Field(
            alias="authorizationEnabled",
            description="Flag that indicates whether users can authorize access to MongoDB Cloud resources using an Lightweight Directory Access Protocol (LDAP) host.",
        ),
    ] = None
    authz_query_template: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="authzQueryTemplate"),
        pydantic.Field(
            alias="authzQueryTemplate",
            description="Lightweight Directory Access Protocol (LDAP) query template that MongoDB Cloud runs to obtain the LDAP groups associated with the authenticated user. MongoDB Cloud uses this parameter only for user authorization. Use the `{USER}` placeholder in the Uniform Resource Locator (URL) to substitute the authenticated username. The query relates to the host specified with the hostname. Format this query according to [RFC 4515](https://datatracker.ietf.org/doc/html/rfc4515) and [RFC 4516](https://datatracker.ietf.org/doc/html/rfc4516).",
        ),
    ] = None
    bind_password: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="bindPassword"),
        pydantic.Field(
            alias="bindPassword", description="Password that MongoDB Cloud uses to authenticate the `bindUsername`."
        ),
    ] = None
    bind_username: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="bindUsername"),
        pydantic.Field(
            alias="bindUsername",
            description="Full Distinguished Name (DN) of the Lightweight Directory Access Protocol (LDAP) user that MongoDB Cloud uses to connect to the LDAP host. LDAP distinguished names must be formatted according to RFC 2253.",
        ),
    ] = None
    ca_certificate: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="caCertificate"),
        pydantic.Field(
            alias="caCertificate",
            description='Certificate Authority (CA) certificate that MongoDB Cloud uses to verify the identity of the Lightweight Directory Access Protocol (LDAP) host. MongoDB Cloud allows self-signed certificates. To delete an assigned value, pass an empty string: `"caCertificate": ""`.',
        ),
    ] = None
    hostname: typing.Optional[str] = pydantic.Field(default=None)
    """
    Human-readable label that identifies the hostname or Internet Protocol (IP) address of the Lightweight Directory Access Protocol (LDAP) host. This host must have access to the internet or have a Virtual Private Cloud (VPC) peering connection to your cluster.
    """

    links: typing.Optional[typing.List[Link]] = pydantic.Field(default=None)
    """
    List of one or more Uniform Resource Locators (URLs) that point to API sub-resources, related API resources, or both. RFC 5988 outlines these relationships.
    """

    port: typing.Optional[int] = pydantic.Field(default=None)
    """
    Port to which the Lightweight Directory Access Protocol (LDAP) host listens for client connections.
    """

    user_to_dn_mapping: typing_extensions.Annotated[
        typing.Optional[typing.List[UserToDnMapping]],
        FieldMetadata(alias="userToDNMapping"),
        pydantic.Field(
            alias="userToDNMapping",
            description="User-to-Distinguished Name (DN) map that MongoDB Cloud uses to transform a Lightweight Directory Access Protocol (LDAP) username into an LDAP DN.",
        ),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
