# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .region_spec import RegionSpec


class LegacyReplicationSpec(UniversalBaseModel):
    id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Unique 24-hexadecimal digit string that identifies the replication object for a zone in a Global Cluster.
    
    - If you include existing zones in the request, you must specify this parameter.
    
    - If you add a new zone to an existing Global Cluster, you may specify this parameter. The request deletes any existing zones in a Global Cluster that you exclude from the request.
    """

    num_shards: typing_extensions.Annotated[
        typing.Optional[int],
        FieldMetadata(alias="numShards"),
        pydantic.Field(
            alias="numShards",
            description="Positive integer that specifies the number of shards to deploy in each specified zone If you set this value to `1` and `clusterType` is `SHARDED`, MongoDB Cloud deploys a single-shard sharded cluster. Don't create a sharded cluster with a single shard for production environments. Single-shard sharded clusters don't provide the same benefits as multi-shard configurations.\n\n If you are upgrading a replica set to a sharded cluster, you cannot increase the number of shards in the same update request.  You should wait until after the cluster has completed upgrading to sharded and you have reconnected all application clients to the MongoDB router before adding additional shards. Otherwise, your data might become inconsistent once MongoDB Cloud begins distributing data across shards.",
        ),
    ] = None
    regions_config: typing_extensions.Annotated[
        typing.Optional[typing.Dict[str, RegionSpec]],
        FieldMetadata(alias="regionsConfig"),
        pydantic.Field(
            alias="regionsConfig", description="Physical location where MongoDB Cloud provisions cluster nodes."
        ),
    ] = None
    zone_name: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="zoneName"),
        pydantic.Field(
            alias="zoneName",
            description="Human-readable label that identifies the zone in a Global Cluster. Provide this value only if `clusterType` is `GEOSHARDED`.",
        ),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
