# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class LiveMigrationResponse(UniversalBaseModel):
    id: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="_id"),
        pydantic.Field(
            alias="_id", description="Unique 24-hexadecimal digit string that identifies the migration job."
        ),
    ] = None
    lag_time_seconds: typing_extensions.Annotated[
        typing.Optional[int],
        FieldMetadata(alias="lagTimeSeconds"),
        pydantic.Field(
            alias="lagTimeSeconds",
            description="Replication lag between the source and destination clusters. Atlas returns this setting only during an active migration, before the cutover phase.",
        ),
    ] = None
    migration_hosts: typing_extensions.Annotated[
        typing.Optional[typing.List[str]],
        FieldMetadata(alias="migrationHosts"),
        pydantic.Field(
            alias="migrationHosts",
            description="List of hosts running MongoDB Agents. These Agents can transfer your MongoDB data between one source and one destination cluster.",
        ),
    ] = None
    ready_for_cutover: typing_extensions.Annotated[
        typing.Optional[bool],
        FieldMetadata(alias="readyForCutover"),
        pydantic.Field(
            alias="readyForCutover",
            description="Flag that indicates the migrated cluster can be cut over to MongoDB Atlas.",
        ),
    ] = None
    status: typing.Optional[str] = pydantic.Field(default=None)
    """
    Progress made in migrating one cluster to MongoDB Atlas.
    
    `NEW`: Someone scheduled a local cluster migration to MongoDB Atlas.
    
    `FAILED`: The cluster migration to MongoDB Atlas failed.
    
    `COMPLETE`: The cluster migration to MongoDB Atlas succeeded.
    
    `EXPIRED`: MongoDB Atlas prepares to begin the cut over of the migrating cluster when source and destination clusters have almost synchronized. If `"readyForCutover" : true`, this synchronization starts a timer of 120 hours. You can extend this timer. If the timer expires, MongoDB Atlas returns this status.
    
    `WORKING`: The cluster migration to MongoDB Atlas is performing one of the following tasks:
    
    - Preparing connections to source and destination clusters.
    - Replicating data from source to destination.
    - Verifying MongoDB Atlas connection settings.
    - Stopping replication after the cut over.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
