# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .namespace_obj import NamespaceObj


class Namespaces(UniversalBaseModel):
    namespaces: typing.Optional[typing.List[NamespaceObj]] = pydantic.Field(default=None)
    """
    List that contains each combination of database, collection, and type on the specified host.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
