# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .custom_session_timeouts import CustomSessionTimeouts


class OrganizationSettings(UniversalBaseModel):
    """
    Collection of settings that configures the organization.
    """

    api_access_list_required: typing_extensions.Annotated[
        typing.Optional[bool],
        FieldMetadata(alias="apiAccessListRequired"),
        pydantic.Field(
            alias="apiAccessListRequired",
            description="Flag that indicates whether to require API operations to originate from an IP Address added to the API access list for the specified organization.",
        ),
    ] = None
    custom_session_timeouts: typing_extensions.Annotated[
        typing.Optional[CustomSessionTimeouts],
        FieldMetadata(alias="customSessionTimeouts"),
        pydantic.Field(alias="customSessionTimeouts"),
    ] = None
    gen_ai_features_enabled: typing_extensions.Annotated[
        typing.Optional[bool],
        FieldMetadata(alias="genAIFeaturesEnabled"),
        pydantic.Field(
            alias="genAIFeaturesEnabled",
            description="Flag that indicates whether this organization has access to generative AI features. This setting only applies to Atlas Commercial and is enabled by default. Once this setting is turned on, Project Owners may be able to enable or disable individual AI features at the project level.",
        ),
    ] = None
    max_service_account_secret_validity_in_hours: typing_extensions.Annotated[
        typing.Optional[int],
        FieldMetadata(alias="maxServiceAccountSecretValidityInHours"),
        pydantic.Field(
            alias="maxServiceAccountSecretValidityInHours",
            description="Number that represents the maximum period before expiry in hours for new Atlas Admin API Service Account secrets within the specified organization.",
        ),
    ] = None
    multi_factor_auth_required: typing_extensions.Annotated[
        typing.Optional[bool],
        FieldMetadata(alias="multiFactorAuthRequired"),
        pydantic.Field(
            alias="multiFactorAuthRequired",
            description="Flag that indicates whether to require users to set up Multi-Factor Authentication (MFA) before accessing the specified organization. To learn more, see: https://www.mongodb.com/docs/atlas/security-multi-factor-authentication/.",
        ),
    ] = None
    restrict_employee_access: typing_extensions.Annotated[
        typing.Optional[bool],
        FieldMetadata(alias="restrictEmployeeAccess"),
        pydantic.Field(
            alias="restrictEmployeeAccess",
            description="Flag that indicates whether to block MongoDB Support from accessing Atlas infrastructure and cluster logs for any deployment in the specified organization without explicit permission. Once this setting is turned on, you can grant MongoDB Support a 24-hour bypass access to the Atlas deployment to resolve support issues. To learn more, see: https://www.mongodb.com/docs/atlas/security-restrict-support-access/.",
        ),
    ] = None
    security_contact: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="securityContact"),
        pydantic.Field(
            alias="securityContact",
            description="String that specifies a single email address for the specified organization to receive security-related notifications. Specifying a security contact does not grant them authorization or access to Atlas for security decisions or approvals. An empty string is valid and clears the existing security contact (if any).",
        ),
    ] = None
    streams_cross_group_enabled: typing_extensions.Annotated[
        typing.Optional[bool],
        FieldMetadata(alias="streamsCrossGroupEnabled"),
        pydantic.Field(
            alias="streamsCrossGroupEnabled",
            description="Flag that indicates whether a group's Atlas Stream Processing workspaces in this organization can create connections to other group's clusters in the same organization.",
        ),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
