# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class PerformanceAdvisorIndex(UniversalBaseModel):
    avg_obj_size: typing_extensions.Annotated[
        typing.Optional[float],
        FieldMetadata(alias="avgObjSize"),
        pydantic.Field(
            alias="avgObjSize", description="The average size of an object in the collection of this index."
        ),
    ] = None
    id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Unique 24-hexadecimal digit string that identifies this index.
    """

    impact: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    List that contains unique 24-hexadecimal character string that identifies the query shapes in this response that the Performance Advisor suggests.
    """

    index: typing.Optional[typing.List[typing.Dict[str, int]]] = pydantic.Field(default=None)
    """
    List that contains documents that specify a key in the index and its sort order.
    """

    namespace: typing.Optional[str] = pydantic.Field(default=None)
    """
    Human-readable label that identifies the namespace on the specified host. The resource expresses this parameter value as `<database>.<collection>`.
    """

    weight: typing.Optional[float] = pydantic.Field(default=None)
    """
    Estimated performance improvement that the suggested index provides. This value corresponds to **Impact** in the Performance Advisor user interface.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
