# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class PrivateEndpointHostname(UniversalBaseModel):
    """
    Set of Private endpoint and hostnames.
    """

    hostname: typing.Optional[str] = pydantic.Field(default=None)
    """
    Human-readable label that identifies the hostname.
    """

    private_endpoint: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="privateEndpoint"),
        pydantic.Field(alias="privateEndpoint", description="Human-readable label that identifies private endpoint."),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
