# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class QueryShapeSeenMetadata(UniversalBaseModel):
    """
    Metadata about when a query shape was seen.
    """

    application_name: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="applicationName"),
        pydantic.Field(
            alias="applicationName",
            description="The name of the application that this query shape came from. This can be set via the MongoDB connection string. The application name is set to unknown for internal MongoDB queries.",
        ),
    ] = None
    driver_name: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="driverName"),
        pydantic.Field(
            alias="driverName",
            description="The name of the MongoDB driver that this query shape was executed from. The driver name is set to unknown for internal MongoDB queries.",
        ),
    ] = None
    driver_version: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="driverVersion"),
        pydantic.Field(
            alias="driverVersion",
            description="The version of the MongoDB driver that this query shape was executed from. The driver version is set to unknown for internal MongoDB queries.",
        ),
    ] = None
    timestamp: typing.Optional[int] = pydantic.Field(default=None)
    """
    Unix epoch milliseconds of the time.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
