# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class RateLimitEndpointSetRefillDurationSeconds(UniversalBaseModel):
    """
    The rate limit refill duration for the endpoint set.
    """

    default_value: typing_extensions.Annotated[
        typing.Optional[int],
        FieldMetadata(alias="defaultValue"),
        pydantic.Field(
            alias="defaultValue",
            description="The default rate limit refill duration, in seconds, of the endpoint set. Returned if there is a rate limit refill duration override set for the requested entity.",
        ),
    ] = None
    value: typing.Optional[int] = pydantic.Field(default=None)
    """
    The applied rate limit refill duration of the endpoint set.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
