# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .rate_limit_endpoint_set_capacity import RateLimitEndpointSetCapacity
from .rate_limit_endpoint_set_endpoint import RateLimitEndpointSetEndpoint
from .rate_limit_endpoint_set_refill_duration_seconds import RateLimitEndpointSetRefillDurationSeconds
from .rate_limit_endpoint_set_refill_rate import RateLimitEndpointSetRefillRate


class RateLimitEndpointSetResponse(UniversalBaseModel):
    capacity: typing.Optional[RateLimitEndpointSetCapacity] = None
    endpoint_set_id: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="endpointSetId"),
        pydantic.Field(alias="endpointSetId", description="The ID of the endpoint set."),
    ] = None
    endpoint_set_name: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="endpointSetName"),
        pydantic.Field(alias="endpointSetName", description="The endpoint set name."),
    ] = None
    endpoints: typing.Optional[typing.List[RateLimitEndpointSetEndpoint]] = pydantic.Field(default=None)
    """
    A list of endpoints associated with the specified endpoint set.
    """

    refill_duration_seconds: typing_extensions.Annotated[
        typing.Optional[RateLimitEndpointSetRefillDurationSeconds],
        FieldMetadata(alias="refillDurationSeconds"),
        pydantic.Field(alias="refillDurationSeconds"),
    ] = None
    refill_rate: typing_extensions.Annotated[
        typing.Optional[RateLimitEndpointSetRefillRate],
        FieldMetadata(alias="refillRate"),
        pydantic.Field(alias="refillRate"),
    ] = None
    scope: typing.Optional[str] = pydantic.Field(default=None)
    """
    The scope of the endpoint set.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
