# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class SearchIndexDefinitionVersion(UniversalBaseModel):
    """
    Object which includes the version number of the index definition and the time that the index definition was created.
    """

    created_at: typing_extensions.Annotated[
        typing.Optional[dt.datetime],
        FieldMetadata(alias="createdAt"),
        pydantic.Field(
            alias="createdAt",
            description="The time at which this index definition was created. This parameter expresses its value in the ISO 8601 timestamp format in UTC.",
        ),
    ] = None
    version: typing.Optional[int] = pydantic.Field(default=None)
    """
    The version number associated with this index definition when it was created.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
