# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .serverless_connection_strings_private_endpoint_item import ServerlessConnectionStringsPrivateEndpointItem


class ServerlessConnectionStringsPrivateEndpointList(UniversalBaseModel):
    """
    Private endpoint connection string that you can use to connect to this serverless instance through a private endpoint.
    """

    endpoints: typing.Optional[typing.List[ServerlessConnectionStringsPrivateEndpointItem]] = pydantic.Field(
        default=None
    )
    """
    List that contains the private endpoints through which you connect to MongoDB Cloud when you use `connectionStrings.privateEndpoint[n].srvConnectionString`.
    """

    srv_connection_string: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="srvConnectionString"),
        pydantic.Field(
            alias="srvConnectionString",
            description="Private endpoint-aware connection string that uses the `mongodb+srv://` protocol to connect to MongoDB Cloud through a private endpoint. The `mongodb+srv` protocol tells the driver to look up the seed list of hosts in the Domain Name System (DNS).",
        ),
    ] = None
    type: typing.Optional[str] = pydantic.Field(default=None)
    """
    MongoDB process type to which your application connects.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
