# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class ShardKeys(UniversalBaseModel):
    """
    Document that configures the shard key on the destination cluster.
    """

    key: typing.List[typing.Dict[str, typing.Any]] = pydantic.Field()
    """
    List of fields to use for the shard key.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
