# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .link import Link


class StreamConfig(UniversalBaseModel):
    """
    Configuration options for an Atlas Stream Processing Workspace.
    """

    links: typing.Optional[typing.List[Link]] = pydantic.Field(default=None)
    """
    List of one or more Uniform Resource Locators (URLs) that point to API sub-resources, related API resources, or both. RFC 5988 outlines these relationships.
    """

    max_tier_size: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="maxTierSize"),
        pydantic.Field(
            alias="maxTierSize",
            description="Max tier size for the Stream Workspace. Configures Memory / VCPU allowances.",
        ),
    ] = None
    tier: typing.Optional[str] = pydantic.Field(default=None)
    """
    Selected tier for the Stream Workspace. Configures Memory / VCPU allowances.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
