# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .link import Link


class StreamsAwsConnectionConfig(UniversalBaseModel):
    """
    AWS configurations for AWS-based connection types.
    """

    links: typing.Optional[typing.List[Link]] = pydantic.Field(default=None)
    """
    List of one or more Uniform Resource Locators (URLs) that point to API sub-resources, related API resources, or both. RFC 5988 outlines these relationships.
    """

    role_arn: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="roleArn"),
        pydantic.Field(
            alias="roleArn",
            description="Amazon Resource Name (ARN) that identifies the Amazon Web Services (AWS) Identity and Access Management (IAM) role that MongoDB Cloud assumes when it accesses resources in your AWS account.",
        ),
    ] = None
    test_bucket: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="testBucket"),
        pydantic.Field(
            alias="testBucket",
            description="The name of an S3 bucket used to check authorization of the passed-in IAM role ARN.",
        ),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
