# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .basic_db_object import BasicDbObject


class VectorSearchIndexDefinition(UniversalBaseModel):
    """
    The vector search index definition set by the user.
    """

    fields: typing.List[BasicDbObject] = pydantic.Field()
    """
    Settings that configure the fields, one per object, to index. You must define at least one "vector" type field. You can optionally define "filter" type fields also.
    """

    nested_root: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="nestedRoot"),
        pydantic.Field(
            alias="nestedRoot",
            description="Top-level path to the array that contains vector fields. When provided, vector fields under this path are treated as nested.",
        ),
    ] = None
    num_partitions: typing_extensions.Annotated[
        typing.Optional[int],
        FieldMetadata(alias="numPartitions"),
        pydantic.Field(alias="numPartitions", description="Number of index partitions. Allowed values are [1, 2, 4]."),
    ] = None
    stored_source: typing_extensions.Annotated[
        typing.Optional[typing.Dict[str, typing.Any]],
        FieldMetadata(alias="storedSource"),
        pydantic.Field(
            alias="storedSource",
            description="Flag that indicates whether to store all fields (true) on Atlas Search. By default, Atlas doesn't store (false) the fields on Atlas Search.  Alternatively, you can specify an object that only contains the list of fields to store (include) or not store (exclude) on Atlas Search. Note that storing all fields (true) is not allowed for vector search indexes. To learn more, see Stored Source Fields.",
        ),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
