# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.flex_backup_restore_job20241113 import FlexBackupRestoreJob20241113
from ..types.paginated_api_atlas_flex_backup_restore_job20241113 import PaginatedApiAtlasFlexBackupRestoreJob20241113
from .raw_client import AsyncRawFlexRestoreJobsClient, RawFlexRestoreJobsClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class FlexRestoreJobsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawFlexRestoreJobsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawFlexRestoreJobsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawFlexRestoreJobsClient
        """
        return self._raw_client

    def list_flex_restore_jobs(
        self,
        group_id: str,
        name: str,
        *,
        include_count: typing.Optional[bool] = None,
        items_per_page: typing.Optional[int] = None,
        page_num: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PaginatedApiAtlasFlexBackupRestoreJob20241113:
        """
        Returns all restore jobs for one flex cluster from the specified project. To use this resource, the requesting Service Account or API Key must have the Project Read Only role.

        Parameters
        ----------
        group_id : str
            Unique 24-hexadecimal digit string that identifies your project. Use the [/groups](#tag/Projects/operation/listProjects) endpoint to retrieve all projects to which the authenticated user has access.

            **NOTE**: Groups and projects are synonymous terms. Your group id is the same as your project id. For existing groups, your group/project id remains the same. The resource and corresponding endpoints use the term groups.

        name : str
            Human-readable label that identifies the flex cluster.

        include_count : typing.Optional[bool]
            Flag that indicates whether the response returns the total number of items (`totalCount`) in the response.

        items_per_page : typing.Optional[int]
            Number of items that the response returns per page.

        page_num : typing.Optional[int]
            Number of the page that displays the current set of the total objects that the response returns.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PaginatedApiAtlasFlexBackupRestoreJob20241113
            OK

        Examples
        --------
        from atlas_sdk import AtlasClient

        client = AtlasClient(
            token="YOUR_TOKEN",
        )
        client.flex_restore_jobs.list_flex_restore_jobs(
            group_id="32b6e34b3d91647abb20e7b8",
            name="name",
        )
        """
        _response = self._raw_client.list_flex_restore_jobs(
            group_id,
            name,
            include_count=include_count,
            items_per_page=items_per_page,
            page_num=page_num,
            request_options=request_options,
        )
        return _response.data

    def create_flex_restore_job(
        self,
        group_id: str,
        name: str,
        *,
        snapshot_id: str,
        target_deployment_item_name: str,
        target_project_id: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> FlexBackupRestoreJob20241113:
        """
        Restores one snapshot of one flex cluster from the specified project. To use this resource, the requesting Service Account or API Key must have the Project Owner role or Project Backup Recovery Operator role.

        Parameters
        ----------
        group_id : str
            Unique 24-hexadecimal digit string that identifies your project. Use the [/groups](#tag/Projects/operation/listProjects) endpoint to retrieve all projects to which the authenticated user has access.

            **NOTE**: Groups and projects are synonymous terms. Your group id is the same as your project id. For existing groups, your group/project id remains the same. The resource and corresponding endpoints use the term groups.

        name : str
            Human-readable label that identifies the flex cluster whose snapshot you want to restore.

        snapshot_id : str
            Unique 24-hexadecimal digit string that identifies the snapshot to restore.

        target_deployment_item_name : str
            Human-readable label that identifies the instance or cluster on the target project to which you want to restore the snapshot. You can restore the snapshot to another flex cluster or dedicated cluster tier.

        target_project_id : typing.Optional[str]
            Unique 24-hexadecimal digit string that identifies the project that contains the instance or cluster to which you want to restore the snapshot.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        FlexBackupRestoreJob20241113
            OK

        Examples
        --------
        from atlas_sdk import AtlasClient

        client = AtlasClient(
            token="YOUR_TOKEN",
        )
        client.flex_restore_jobs.create_flex_restore_job(
            group_id="32b6e34b3d91647abb20e7b8",
            name="name",
            snapshot_id="32b6e34b3d91647abb20e7b8",
            target_deployment_item_name="targetDeploymentItemName",
        )
        """
        _response = self._raw_client.create_flex_restore_job(
            group_id,
            name,
            snapshot_id=snapshot_id,
            target_deployment_item_name=target_deployment_item_name,
            target_project_id=target_project_id,
            request_options=request_options,
        )
        return _response.data

    def get_flex_restore_job(
        self, group_id: str, name: str, restore_job_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> FlexBackupRestoreJob20241113:
        """
        Returns one restore job for one flex cluster from the specified project. To use this resource, the requesting Service Account or API Key must have the Project Read Only role.

        Parameters
        ----------
        group_id : str
            Unique 24-hexadecimal digit string that identifies your project. Use the [/groups](#tag/Projects/operation/listProjects) endpoint to retrieve all projects to which the authenticated user has access.

            **NOTE**: Groups and projects are synonymous terms. Your group id is the same as your project id. For existing groups, your group/project id remains the same. The resource and corresponding endpoints use the term groups.

        name : str
            Human-readable label that identifies the flex cluster.

        restore_job_id : str
            Unique 24-hexadecimal digit string that identifies the restore job to return.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        FlexBackupRestoreJob20241113
            OK

        Examples
        --------
        from atlas_sdk import AtlasClient

        client = AtlasClient(
            token="YOUR_TOKEN",
        )
        client.flex_restore_jobs.get_flex_restore_job(
            group_id="32b6e34b3d91647abb20e7b8",
            name="name",
            restore_job_id="restoreJobId",
        )
        """
        _response = self._raw_client.get_flex_restore_job(
            group_id, name, restore_job_id, request_options=request_options
        )
        return _response.data


class AsyncFlexRestoreJobsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawFlexRestoreJobsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawFlexRestoreJobsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawFlexRestoreJobsClient
        """
        return self._raw_client

    async def list_flex_restore_jobs(
        self,
        group_id: str,
        name: str,
        *,
        include_count: typing.Optional[bool] = None,
        items_per_page: typing.Optional[int] = None,
        page_num: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PaginatedApiAtlasFlexBackupRestoreJob20241113:
        """
        Returns all restore jobs for one flex cluster from the specified project. To use this resource, the requesting Service Account or API Key must have the Project Read Only role.

        Parameters
        ----------
        group_id : str
            Unique 24-hexadecimal digit string that identifies your project. Use the [/groups](#tag/Projects/operation/listProjects) endpoint to retrieve all projects to which the authenticated user has access.

            **NOTE**: Groups and projects are synonymous terms. Your group id is the same as your project id. For existing groups, your group/project id remains the same. The resource and corresponding endpoints use the term groups.

        name : str
            Human-readable label that identifies the flex cluster.

        include_count : typing.Optional[bool]
            Flag that indicates whether the response returns the total number of items (`totalCount`) in the response.

        items_per_page : typing.Optional[int]
            Number of items that the response returns per page.

        page_num : typing.Optional[int]
            Number of the page that displays the current set of the total objects that the response returns.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PaginatedApiAtlasFlexBackupRestoreJob20241113
            OK

        Examples
        --------
        import asyncio

        from atlas_sdk import AsyncAtlasClient

        client = AsyncAtlasClient(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.flex_restore_jobs.list_flex_restore_jobs(
                group_id="32b6e34b3d91647abb20e7b8",
                name="name",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list_flex_restore_jobs(
            group_id,
            name,
            include_count=include_count,
            items_per_page=items_per_page,
            page_num=page_num,
            request_options=request_options,
        )
        return _response.data

    async def create_flex_restore_job(
        self,
        group_id: str,
        name: str,
        *,
        snapshot_id: str,
        target_deployment_item_name: str,
        target_project_id: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> FlexBackupRestoreJob20241113:
        """
        Restores one snapshot of one flex cluster from the specified project. To use this resource, the requesting Service Account or API Key must have the Project Owner role or Project Backup Recovery Operator role.

        Parameters
        ----------
        group_id : str
            Unique 24-hexadecimal digit string that identifies your project. Use the [/groups](#tag/Projects/operation/listProjects) endpoint to retrieve all projects to which the authenticated user has access.

            **NOTE**: Groups and projects are synonymous terms. Your group id is the same as your project id. For existing groups, your group/project id remains the same. The resource and corresponding endpoints use the term groups.

        name : str
            Human-readable label that identifies the flex cluster whose snapshot you want to restore.

        snapshot_id : str
            Unique 24-hexadecimal digit string that identifies the snapshot to restore.

        target_deployment_item_name : str
            Human-readable label that identifies the instance or cluster on the target project to which you want to restore the snapshot. You can restore the snapshot to another flex cluster or dedicated cluster tier.

        target_project_id : typing.Optional[str]
            Unique 24-hexadecimal digit string that identifies the project that contains the instance or cluster to which you want to restore the snapshot.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        FlexBackupRestoreJob20241113
            OK

        Examples
        --------
        import asyncio

        from atlas_sdk import AsyncAtlasClient

        client = AsyncAtlasClient(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.flex_restore_jobs.create_flex_restore_job(
                group_id="32b6e34b3d91647abb20e7b8",
                name="name",
                snapshot_id="32b6e34b3d91647abb20e7b8",
                target_deployment_item_name="targetDeploymentItemName",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_flex_restore_job(
            group_id,
            name,
            snapshot_id=snapshot_id,
            target_deployment_item_name=target_deployment_item_name,
            target_project_id=target_project_id,
            request_options=request_options,
        )
        return _response.data

    async def get_flex_restore_job(
        self, group_id: str, name: str, restore_job_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> FlexBackupRestoreJob20241113:
        """
        Returns one restore job for one flex cluster from the specified project. To use this resource, the requesting Service Account or API Key must have the Project Read Only role.

        Parameters
        ----------
        group_id : str
            Unique 24-hexadecimal digit string that identifies your project. Use the [/groups](#tag/Projects/operation/listProjects) endpoint to retrieve all projects to which the authenticated user has access.

            **NOTE**: Groups and projects are synonymous terms. Your group id is the same as your project id. For existing groups, your group/project id remains the same. The resource and corresponding endpoints use the term groups.

        name : str
            Human-readable label that identifies the flex cluster.

        restore_job_id : str
            Unique 24-hexadecimal digit string that identifies the restore job to return.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        FlexBackupRestoreJob20241113
            OK

        Examples
        --------
        import asyncio

        from atlas_sdk import AsyncAtlasClient

        client = AsyncAtlasClient(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.flex_restore_jobs.get_flex_restore_job(
                group_id="32b6e34b3d91647abb20e7b8",
                name="name",
                restore_job_id="restoreJobId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_flex_restore_job(
            group_id, name, restore_job_id, request_options=request_options
        )
        return _response.data
