# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.awskms_configuration import AwskmsConfiguration
from ..types.azure_key_vault import AzureKeyVault
from ..types.ear_private_endpoint import EarPrivateEndpoint
from ..types.encryption_at_rest import EncryptionAtRest
from ..types.google_cloud_kms import GoogleCloudKms
from ..types.paginated_api_atlas_ear_private_endpoint import PaginatedApiAtlasEarPrivateEndpoint
from .raw_client import (
    AsyncRawEncryptionAtRestUsingCustomerKeyManagementClient,
    RawEncryptionAtRestUsingCustomerKeyManagementClient,
)

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class EncryptionAtRestUsingCustomerKeyManagementClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawEncryptionAtRestUsingCustomerKeyManagementClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawEncryptionAtRestUsingCustomerKeyManagementClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawEncryptionAtRestUsingCustomerKeyManagementClient
        """
        return self._raw_client

    def get_encryption_at_rest(
        self, group_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> EncryptionAtRest:
        """
        Returns the configuration for encryption at rest using the keys you manage through your cloud provider. MongoDB Cloud encrypts all storage even if you don't use your own key management. This resource requires the requesting Service Account or API Key to have the Project Owner role.

        **LIMITED TO M10 OR GREATER:** MongoDB Cloud limits this feature to dedicated cluster tiers of M10 and greater.

        Parameters
        ----------
        group_id : str
            Unique 24-hexadecimal digit string that identifies your project. Use the [/groups](#tag/Projects/operation/listProjects) endpoint to retrieve all projects to which the authenticated user has access.

            **NOTE**: Groups and projects are synonymous terms. Your group id is the same as your project id. For existing groups, your group/project id remains the same. The resource and corresponding endpoints use the term groups.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        EncryptionAtRest
            OK

        Examples
        --------
        from atlas_sdk import AtlasClient

        client = AtlasClient(
            token="YOUR_TOKEN",
        )
        client.encryption_at_rest_using_customer_key_management.get_encryption_at_rest(
            group_id="32b6e34b3d91647abb20e7b8",
        )
        """
        _response = self._raw_client.get_encryption_at_rest(group_id, request_options=request_options)
        return _response.data

    def update_encryption_at_rest(
        self,
        group_id: str,
        *,
        aws_kms: typing.Optional[AwskmsConfiguration] = OMIT,
        azure_key_vault: typing.Optional[AzureKeyVault] = OMIT,
        enabled_for_search_nodes: typing.Optional[bool] = OMIT,
        google_cloud_kms: typing.Optional[GoogleCloudKms] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> EncryptionAtRest:
        """
        Updates the configuration for encryption at rest using the keys you manage through your cloud provider. MongoDB Cloud encrypts all storage even if you don't use your own key management. This resource requires the requesting Service Account or API Key to have the Project Owner role. This feature isn't available for `M0` free clusters, `M2`, `M5`, or serverless clusters.

         After you configure at least one Encryption at Rest using a Customer Key Management provider for the MongoDB Cloud project, Project Owners can enable Encryption at Rest using Customer Key Management for each MongoDB Cloud cluster for which they require encryption. The Encryption at Rest using Customer Key Management provider doesn't have to match the cluster cloud service provider. MongoDB Cloud doesn't automatically rotate user-managed encryption keys. Defer to your preferred Encryption at Rest using Customer Key Management provider's documentation and guidance for best practices on key rotation. MongoDB Cloud automatically creates a 90-day key rotation alert when you configure Encryption at Rest using Customer Key Management using your Key Management in an MongoDB Cloud project. MongoDB Cloud encrypts all storage whether or not you use your own key management.

        Parameters
        ----------
        group_id : str
            Unique 24-hexadecimal digit string that identifies your project. Use the [/groups](#tag/Projects/operation/listProjects) endpoint to retrieve all projects to which the authenticated user has access.

            **NOTE**: Groups and projects are synonymous terms. Your group id is the same as your project id. For existing groups, your group/project id remains the same. The resource and corresponding endpoints use the term groups.

        aws_kms : typing.Optional[AwskmsConfiguration]

        azure_key_vault : typing.Optional[AzureKeyVault]

        enabled_for_search_nodes : typing.Optional[bool]
            Flag that indicates whether Encryption at Rest for Dedicated Search Nodes is enabled in the specified project.

        google_cloud_kms : typing.Optional[GoogleCloudKms]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        EncryptionAtRest
            OK

        Examples
        --------
        from atlas_sdk import AtlasClient

        client = AtlasClient(
            token="YOUR_TOKEN",
        )
        client.encryption_at_rest_using_customer_key_management.update_encryption_at_rest(
            group_id="32b6e34b3d91647abb20e7b8",
        )
        """
        _response = self._raw_client.update_encryption_at_rest(
            group_id,
            aws_kms=aws_kms,
            azure_key_vault=azure_key_vault,
            enabled_for_search_nodes=enabled_for_search_nodes,
            google_cloud_kms=google_cloud_kms,
            request_options=request_options,
        )
        return _response.data

    def list_rest_private_endpoints(
        self,
        group_id: str,
        cloud_provider: str,
        *,
        include_count: typing.Optional[bool] = None,
        items_per_page: typing.Optional[int] = None,
        page_num: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PaginatedApiAtlasEarPrivateEndpoint:
        """
        Returns the private endpoints of the specified cloud provider for encryption at rest using customer key management.

        Parameters
        ----------
        group_id : str
            Unique 24-hexadecimal digit string that identifies your project. Use the [/groups](#tag/Projects/operation/listProjects) endpoint to retrieve all projects to which the authenticated user has access.

            **NOTE**: Groups and projects are synonymous terms. Your group id is the same as your project id. For existing groups, your group/project id remains the same. The resource and corresponding endpoints use the term groups.

        cloud_provider : str
            Human-readable label that identifies the cloud provider for the private endpoints to return.

        include_count : typing.Optional[bool]
            Flag that indicates whether the response returns the total number of items (`totalCount`) in the response.

        items_per_page : typing.Optional[int]
            Number of items that the response returns per page.

        page_num : typing.Optional[int]
            Number of the page that displays the current set of the total objects that the response returns.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PaginatedApiAtlasEarPrivateEndpoint
            OK

        Examples
        --------
        from atlas_sdk import AtlasClient

        client = AtlasClient(
            token="YOUR_TOKEN",
        )
        client.encryption_at_rest_using_customer_key_management.list_rest_private_endpoints(
            group_id="32b6e34b3d91647abb20e7b8",
            cloud_provider="cloudProvider",
        )
        """
        _response = self._raw_client.list_rest_private_endpoints(
            group_id,
            cloud_provider,
            include_count=include_count,
            items_per_page=items_per_page,
            page_num=page_num,
            request_options=request_options,
        )
        return _response.data

    def create_rest_private_endpoint(
        self,
        group_id: str,
        cloud_provider_: str,
        *,
        cloud_provider: typing.Optional[str] = OMIT,
        error_message: typing.Optional[str] = OMIT,
        id: typing.Optional[str] = OMIT,
        region_name: typing.Optional[str] = OMIT,
        status: typing.Optional[str] = OMIT,
        private_endpoint_connection_name: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> EarPrivateEndpoint:
        """
        Creates a private endpoint in the specified region for encryption at rest using customer key management.

        Parameters
        ----------
        group_id : str
            Unique 24-hexadecimal digit string that identifies your project. Use the [/groups](#tag/Projects/operation/listProjects) endpoint to retrieve all projects to which the authenticated user has access.

            **NOTE**: Groups and projects are synonymous terms. Your group id is the same as your project id. For existing groups, your group/project id remains the same. The resource and corresponding endpoints use the term groups.

        cloud_provider_ : str
            Human-readable label that identifies the cloud provider for the private endpoint to create.

        cloud_provider : typing.Optional[str]
            Human-readable label that identifies the cloud provider for the Encryption At Rest private endpoint.

        error_message : typing.Optional[str]
            Error message for failures associated with the Encryption At Rest private endpoint.

        id : typing.Optional[str]
            Unique 24-hexadecimal digit string that identifies the Private Endpoint Service.

        region_name : typing.Optional[str]
            Cloud provider region in which the Encryption At Rest private endpoint is located.

        status : typing.Optional[str]
            State of the Encryption At Rest private endpoint.

        private_endpoint_connection_name : typing.Optional[str]
            Resource Id of the Aws Private Endpoint.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        EarPrivateEndpoint
            Accepted

        Examples
        --------
        from atlas_sdk import AtlasClient

        client = AtlasClient(
            token="YOUR_TOKEN",
        )
        client.encryption_at_rest_using_customer_key_management.create_rest_private_endpoint(
            group_id="32b6e34b3d91647abb20e7b8",
            cloud_provider_="cloudProvider",
        )
        """
        _response = self._raw_client.create_rest_private_endpoint(
            group_id,
            cloud_provider_,
            cloud_provider=cloud_provider,
            error_message=error_message,
            id=id,
            region_name=region_name,
            status=status,
            private_endpoint_connection_name=private_endpoint_connection_name,
            request_options=request_options,
        )
        return _response.data

    def get_rest_private_endpoint(
        self,
        group_id: str,
        cloud_provider: str,
        endpoint_id: str,
        *,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> EarPrivateEndpoint:
        """
        Returns one private endpoint, identified by its ID, for encryption at rest using Customer Key Management.

        Parameters
        ----------
        group_id : str
            Unique 24-hexadecimal digit string that identifies your project. Use the [/groups](#tag/Projects/operation/listProjects) endpoint to retrieve all projects to which the authenticated user has access.

            **NOTE**: Groups and projects are synonymous terms. Your group id is the same as your project id. For existing groups, your group/project id remains the same. The resource and corresponding endpoints use the term groups.

        cloud_provider : str
            Human-readable label that identifies the cloud provider of the private endpoint.

        endpoint_id : str
            Unique 24-hexadecimal digit string that identifies the private endpoint.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        EarPrivateEndpoint
            OK

        Examples
        --------
        from atlas_sdk import AtlasClient

        client = AtlasClient(
            token="YOUR_TOKEN",
        )
        client.encryption_at_rest_using_customer_key_management.get_rest_private_endpoint(
            group_id="32b6e34b3d91647abb20e7b8",
            cloud_provider="cloudProvider",
            endpoint_id="endpointId",
        )
        """
        _response = self._raw_client.get_rest_private_endpoint(
            group_id, cloud_provider, endpoint_id, request_options=request_options
        )
        return _response.data

    def request_private_endpoint_deletion(
        self,
        group_id: str,
        cloud_provider: str,
        endpoint_id: str,
        *,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.Any:
        """
        Deletes one private endpoint, identified by its ID, for encryption at rest using Customer Key Management.

        Parameters
        ----------
        group_id : str
            Unique 24-hexadecimal digit string that identifies your project. Use the [/groups](#tag/Projects/operation/listProjects) endpoint to retrieve all projects to which the authenticated user has access.

            **NOTE**: Groups and projects are synonymous terms. Your group id is the same as your project id. For existing groups, your group/project id remains the same. The resource and corresponding endpoints use the term groups.

        cloud_provider : str
            Human-readable label that identifies the cloud provider of the private endpoint to delete.

        endpoint_id : str
            Unique 24-hexadecimal digit string that identifies the private endpoint to delete.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Any
            This endpoint does not return a response body.

        Examples
        --------
        from atlas_sdk import AtlasClient

        client = AtlasClient(
            token="YOUR_TOKEN",
        )
        client.encryption_at_rest_using_customer_key_management.request_private_endpoint_deletion(
            group_id="32b6e34b3d91647abb20e7b8",
            cloud_provider="cloudProvider",
            endpoint_id="endpointId",
        )
        """
        _response = self._raw_client.request_private_endpoint_deletion(
            group_id, cloud_provider, endpoint_id, request_options=request_options
        )
        return _response.data


class AsyncEncryptionAtRestUsingCustomerKeyManagementClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawEncryptionAtRestUsingCustomerKeyManagementClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawEncryptionAtRestUsingCustomerKeyManagementClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawEncryptionAtRestUsingCustomerKeyManagementClient
        """
        return self._raw_client

    async def get_encryption_at_rest(
        self, group_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> EncryptionAtRest:
        """
        Returns the configuration for encryption at rest using the keys you manage through your cloud provider. MongoDB Cloud encrypts all storage even if you don't use your own key management. This resource requires the requesting Service Account or API Key to have the Project Owner role.

        **LIMITED TO M10 OR GREATER:** MongoDB Cloud limits this feature to dedicated cluster tiers of M10 and greater.

        Parameters
        ----------
        group_id : str
            Unique 24-hexadecimal digit string that identifies your project. Use the [/groups](#tag/Projects/operation/listProjects) endpoint to retrieve all projects to which the authenticated user has access.

            **NOTE**: Groups and projects are synonymous terms. Your group id is the same as your project id. For existing groups, your group/project id remains the same. The resource and corresponding endpoints use the term groups.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        EncryptionAtRest
            OK

        Examples
        --------
        import asyncio

        from atlas_sdk import AsyncAtlasClient

        client = AsyncAtlasClient(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.encryption_at_rest_using_customer_key_management.get_encryption_at_rest(
                group_id="32b6e34b3d91647abb20e7b8",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_encryption_at_rest(group_id, request_options=request_options)
        return _response.data

    async def update_encryption_at_rest(
        self,
        group_id: str,
        *,
        aws_kms: typing.Optional[AwskmsConfiguration] = OMIT,
        azure_key_vault: typing.Optional[AzureKeyVault] = OMIT,
        enabled_for_search_nodes: typing.Optional[bool] = OMIT,
        google_cloud_kms: typing.Optional[GoogleCloudKms] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> EncryptionAtRest:
        """
        Updates the configuration for encryption at rest using the keys you manage through your cloud provider. MongoDB Cloud encrypts all storage even if you don't use your own key management. This resource requires the requesting Service Account or API Key to have the Project Owner role. This feature isn't available for `M0` free clusters, `M2`, `M5`, or serverless clusters.

         After you configure at least one Encryption at Rest using a Customer Key Management provider for the MongoDB Cloud project, Project Owners can enable Encryption at Rest using Customer Key Management for each MongoDB Cloud cluster for which they require encryption. The Encryption at Rest using Customer Key Management provider doesn't have to match the cluster cloud service provider. MongoDB Cloud doesn't automatically rotate user-managed encryption keys. Defer to your preferred Encryption at Rest using Customer Key Management provider's documentation and guidance for best practices on key rotation. MongoDB Cloud automatically creates a 90-day key rotation alert when you configure Encryption at Rest using Customer Key Management using your Key Management in an MongoDB Cloud project. MongoDB Cloud encrypts all storage whether or not you use your own key management.

        Parameters
        ----------
        group_id : str
            Unique 24-hexadecimal digit string that identifies your project. Use the [/groups](#tag/Projects/operation/listProjects) endpoint to retrieve all projects to which the authenticated user has access.

            **NOTE**: Groups and projects are synonymous terms. Your group id is the same as your project id. For existing groups, your group/project id remains the same. The resource and corresponding endpoints use the term groups.

        aws_kms : typing.Optional[AwskmsConfiguration]

        azure_key_vault : typing.Optional[AzureKeyVault]

        enabled_for_search_nodes : typing.Optional[bool]
            Flag that indicates whether Encryption at Rest for Dedicated Search Nodes is enabled in the specified project.

        google_cloud_kms : typing.Optional[GoogleCloudKms]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        EncryptionAtRest
            OK

        Examples
        --------
        import asyncio

        from atlas_sdk import AsyncAtlasClient

        client = AsyncAtlasClient(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.encryption_at_rest_using_customer_key_management.update_encryption_at_rest(
                group_id="32b6e34b3d91647abb20e7b8",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update_encryption_at_rest(
            group_id,
            aws_kms=aws_kms,
            azure_key_vault=azure_key_vault,
            enabled_for_search_nodes=enabled_for_search_nodes,
            google_cloud_kms=google_cloud_kms,
            request_options=request_options,
        )
        return _response.data

    async def list_rest_private_endpoints(
        self,
        group_id: str,
        cloud_provider: str,
        *,
        include_count: typing.Optional[bool] = None,
        items_per_page: typing.Optional[int] = None,
        page_num: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PaginatedApiAtlasEarPrivateEndpoint:
        """
        Returns the private endpoints of the specified cloud provider for encryption at rest using customer key management.

        Parameters
        ----------
        group_id : str
            Unique 24-hexadecimal digit string that identifies your project. Use the [/groups](#tag/Projects/operation/listProjects) endpoint to retrieve all projects to which the authenticated user has access.

            **NOTE**: Groups and projects are synonymous terms. Your group id is the same as your project id. For existing groups, your group/project id remains the same. The resource and corresponding endpoints use the term groups.

        cloud_provider : str
            Human-readable label that identifies the cloud provider for the private endpoints to return.

        include_count : typing.Optional[bool]
            Flag that indicates whether the response returns the total number of items (`totalCount`) in the response.

        items_per_page : typing.Optional[int]
            Number of items that the response returns per page.

        page_num : typing.Optional[int]
            Number of the page that displays the current set of the total objects that the response returns.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PaginatedApiAtlasEarPrivateEndpoint
            OK

        Examples
        --------
        import asyncio

        from atlas_sdk import AsyncAtlasClient

        client = AsyncAtlasClient(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.encryption_at_rest_using_customer_key_management.list_rest_private_endpoints(
                group_id="32b6e34b3d91647abb20e7b8",
                cloud_provider="cloudProvider",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list_rest_private_endpoints(
            group_id,
            cloud_provider,
            include_count=include_count,
            items_per_page=items_per_page,
            page_num=page_num,
            request_options=request_options,
        )
        return _response.data

    async def create_rest_private_endpoint(
        self,
        group_id: str,
        cloud_provider_: str,
        *,
        cloud_provider: typing.Optional[str] = OMIT,
        error_message: typing.Optional[str] = OMIT,
        id: typing.Optional[str] = OMIT,
        region_name: typing.Optional[str] = OMIT,
        status: typing.Optional[str] = OMIT,
        private_endpoint_connection_name: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> EarPrivateEndpoint:
        """
        Creates a private endpoint in the specified region for encryption at rest using customer key management.

        Parameters
        ----------
        group_id : str
            Unique 24-hexadecimal digit string that identifies your project. Use the [/groups](#tag/Projects/operation/listProjects) endpoint to retrieve all projects to which the authenticated user has access.

            **NOTE**: Groups and projects are synonymous terms. Your group id is the same as your project id. For existing groups, your group/project id remains the same. The resource and corresponding endpoints use the term groups.

        cloud_provider_ : str
            Human-readable label that identifies the cloud provider for the private endpoint to create.

        cloud_provider : typing.Optional[str]
            Human-readable label that identifies the cloud provider for the Encryption At Rest private endpoint.

        error_message : typing.Optional[str]
            Error message for failures associated with the Encryption At Rest private endpoint.

        id : typing.Optional[str]
            Unique 24-hexadecimal digit string that identifies the Private Endpoint Service.

        region_name : typing.Optional[str]
            Cloud provider region in which the Encryption At Rest private endpoint is located.

        status : typing.Optional[str]
            State of the Encryption At Rest private endpoint.

        private_endpoint_connection_name : typing.Optional[str]
            Resource Id of the Aws Private Endpoint.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        EarPrivateEndpoint
            Accepted

        Examples
        --------
        import asyncio

        from atlas_sdk import AsyncAtlasClient

        client = AsyncAtlasClient(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.encryption_at_rest_using_customer_key_management.create_rest_private_endpoint(
                group_id="32b6e34b3d91647abb20e7b8",
                cloud_provider_="cloudProvider",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_rest_private_endpoint(
            group_id,
            cloud_provider_,
            cloud_provider=cloud_provider,
            error_message=error_message,
            id=id,
            region_name=region_name,
            status=status,
            private_endpoint_connection_name=private_endpoint_connection_name,
            request_options=request_options,
        )
        return _response.data

    async def get_rest_private_endpoint(
        self,
        group_id: str,
        cloud_provider: str,
        endpoint_id: str,
        *,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> EarPrivateEndpoint:
        """
        Returns one private endpoint, identified by its ID, for encryption at rest using Customer Key Management.

        Parameters
        ----------
        group_id : str
            Unique 24-hexadecimal digit string that identifies your project. Use the [/groups](#tag/Projects/operation/listProjects) endpoint to retrieve all projects to which the authenticated user has access.

            **NOTE**: Groups and projects are synonymous terms. Your group id is the same as your project id. For existing groups, your group/project id remains the same. The resource and corresponding endpoints use the term groups.

        cloud_provider : str
            Human-readable label that identifies the cloud provider of the private endpoint.

        endpoint_id : str
            Unique 24-hexadecimal digit string that identifies the private endpoint.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        EarPrivateEndpoint
            OK

        Examples
        --------
        import asyncio

        from atlas_sdk import AsyncAtlasClient

        client = AsyncAtlasClient(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.encryption_at_rest_using_customer_key_management.get_rest_private_endpoint(
                group_id="32b6e34b3d91647abb20e7b8",
                cloud_provider="cloudProvider",
                endpoint_id="endpointId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_rest_private_endpoint(
            group_id, cloud_provider, endpoint_id, request_options=request_options
        )
        return _response.data

    async def request_private_endpoint_deletion(
        self,
        group_id: str,
        cloud_provider: str,
        endpoint_id: str,
        *,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.Any:
        """
        Deletes one private endpoint, identified by its ID, for encryption at rest using Customer Key Management.

        Parameters
        ----------
        group_id : str
            Unique 24-hexadecimal digit string that identifies your project. Use the [/groups](#tag/Projects/operation/listProjects) endpoint to retrieve all projects to which the authenticated user has access.

            **NOTE**: Groups and projects are synonymous terms. Your group id is the same as your project id. For existing groups, your group/project id remains the same. The resource and corresponding endpoints use the term groups.

        cloud_provider : str
            Human-readable label that identifies the cloud provider of the private endpoint to delete.

        endpoint_id : str
            Unique 24-hexadecimal digit string that identifies the private endpoint to delete.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Any
            This endpoint does not return a response body.

        Examples
        --------
        import asyncio

        from atlas_sdk import AsyncAtlasClient

        client = AsyncAtlasClient(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.encryption_at_rest_using_customer_key_management.request_private_endpoint_deletion(
                group_id="32b6e34b3d91647abb20e7b8",
                cloud_provider="cloudProvider",
                endpoint_id="endpointId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.request_private_endpoint_deletion(
            group_id, cloud_provider, endpoint_id, request_options=request_options
        )
        return _response.data
